// Auto-generated testbench for dma_axi32_core0_wdt
// Source: dma_axi32_core0_wdt.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_wdt;

  reg clk;
  reg reset;
  reg [7:0] ch_active;
  reg rd_burst_start;
  reg [2:0] rd_ch_num;
  reg wr_burst_start;
  reg [2:0] wr_ch_num;
  wire wdt_timeout;
  wire [2:0] wdt_ch_num;

  // DUT instantiation
  dma_axi32_core0_wdt dut (
    .clk(clk),
    .reset(reset),
    .ch_active(ch_active),
    .rd_burst_start(rd_burst_start),
    .rd_ch_num(rd_ch_num),
    .wr_burst_start(wr_burst_start),
    .wr_ch_num(wr_ch_num),
    .wdt_timeout(wdt_timeout),
    .wdt_ch_num(wdt_ch_num)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    ch_active = '0;
    rd_ch_num = '0;
    wr_ch_num = '0;
    reset = 1'b1;  // active-high reset asserted
    rd_burst_start = 1'b1;  // active-high reset asserted
    wr_burst_start = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    rd_burst_start = 1'b0;  // release active-high reset
    wr_burst_start = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_wdt compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_wdt");
    $finish;
  end

endmodule
