// Auto-generated testbench for dma_axi32_core0_ch_fifo_ptr
// Source: dma_axi32_core0_ch_fifo_ptr.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_ch_fifo_ptr;

  reg clk;
  reg reset;
  reg joint_in_prog;
  reg wr_outstanding;
  reg ch_update;
  reg fifo_rd;
  reg [2:0] fifo_rsize;
  reg slice_wr;
  reg slice_wr_fifo;
  reg [2:0] slice_wsize;
  reg slice_rd;
  reg [2:0] slice_rsize;
  reg rd_clr_line;
  reg wr_clr_line;
  reg [2:0] wr_next_size;
  reg [6:0] wr_burst_size;
  wire [4:0] rd_ptr;
  wire [4:0] wr_ptr;
  wire [2:0] rd_line_remain;
  wire joint_delay;
  wire fifo_wr_ready;
  wire fifo_overflow;
  wire fifo_underflow;

  // DUT instantiation
  dma_axi32_core0_ch_fifo_ptr dut (
    .clk(clk),
    .reset(reset),
    .joint_in_prog(joint_in_prog),
    .wr_outstanding(wr_outstanding),
    .ch_update(ch_update),
    .fifo_rd(fifo_rd),
    .fifo_rsize(fifo_rsize),
    .slice_wr(slice_wr),
    .slice_wr_fifo(slice_wr_fifo),
    .slice_wsize(slice_wsize),
    .slice_rd(slice_rd),
    .slice_rsize(slice_rsize),
    .rd_clr_line(rd_clr_line),
    .wr_clr_line(wr_clr_line),
    .wr_next_size(wr_next_size),
    .wr_burst_size(wr_burst_size),
    .rd_ptr(rd_ptr),
    .wr_ptr(wr_ptr),
    .rd_line_remain(rd_line_remain),
    .joint_delay(joint_delay),
    .fifo_wr_ready(fifo_wr_ready),
    .fifo_overflow(fifo_overflow),
    .fifo_underflow(fifo_underflow)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    joint_in_prog = '0;
    wr_outstanding = '0;
    ch_update = '0;
    fifo_rd = '0;
    fifo_rsize = '0;
    slice_wr = '0;
    slice_wr_fifo = '0;
    slice_wsize = '0;
    slice_rd = '0;
    slice_rsize = '0;
    rd_clr_line = '0;
    wr_clr_line = '0;
    wr_next_size = '0;
    reset = 1'b1;  // active-high reset asserted
    wr_burst_size = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    wr_burst_size = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_ch_fifo_ptr compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_ch_fifo_ptr");
    $finish;
  end

endmodule
