// Auto-generated testbench for dma_axi32_core0_ch_fifo_ctrl
// Source: dma_axi32_core0_ch_fifo_ctrl.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_ch_fifo_ctrl;

  reg clk;
  reg reset;
  reg [1:0] end_swap;
  reg joint_in_prog;
  reg wr_outstanding;
  reg ch_update;
  reg fifo_wr;
  reg [31:0] fifo_wdata;
  reg [2:0] fifo_wsize;
  reg [1:0] wr_align;
  reg rd_incr;
  reg fifo_rd;
  reg [2:0] fifo_rsize;
  reg [1:0] rd_align;
  reg wr_incr;
  reg wr_single;
  reg [6:0] wr_burst_size;
  reg rd_clr_line;
  reg wr_clr_line;
  reg [2:0] wr_next_size;
  wire fifo_rd_valid;
  wire [31:0] fifo_rdata;
  wire fifo_wr_ready;
  wire fifo_overflow;
  wire fifo_underflow;

  // DUT instantiation
  dma_axi32_core0_ch_fifo_ctrl dut (
    .clk(clk),
    .reset(reset),
    .end_swap(end_swap),
    .joint_in_prog(joint_in_prog),
    .wr_outstanding(wr_outstanding),
    .ch_update(ch_update),
    .fifo_wr(fifo_wr),
    .fifo_wdata(fifo_wdata),
    .fifo_wsize(fifo_wsize),
    .wr_align(wr_align),
    .rd_incr(rd_incr),
    .fifo_rd(fifo_rd),
    .fifo_rsize(fifo_rsize),
    .rd_align(rd_align),
    .wr_incr(wr_incr),
    .wr_single(wr_single),
    .wr_burst_size(wr_burst_size),
    .rd_clr_line(rd_clr_line),
    .wr_clr_line(wr_clr_line),
    .wr_next_size(wr_next_size),
    .fifo_rd_valid(fifo_rd_valid),
    .fifo_rdata(fifo_rdata),
    .fifo_wr_ready(fifo_wr_ready),
    .fifo_overflow(fifo_overflow),
    .fifo_underflow(fifo_underflow)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    end_swap = '0;
    joint_in_prog = '0;
    wr_outstanding = '0;
    ch_update = '0;
    fifo_wr = '0;
    fifo_wdata = '0;
    fifo_wsize = '0;
    wr_align = '0;
    rd_incr = '0;
    fifo_rd = '0;
    fifo_rsize = '0;
    rd_align = '0;
    wr_incr = '0;
    wr_single = '0;
    rd_clr_line = '0;
    wr_clr_line = '0;
    wr_next_size = '0;
    reset = 1'b1;  // active-high reset asserted
    wr_burst_size = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    wr_burst_size = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_ch_fifo_ctrl compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_ch_fifo_ctrl");
    $finish;
  end

endmodule
