// Auto-generated testbench for dma_axi64_core0_arbiter
// Source: dma_axi64_core0_arbiter.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_arbiter;

  reg clk;
  reg reset;
  reg enable;
  reg joint_mode;
  reg page_cross;
  reg joint_req;
  reg prio_top;
  reg prio_high;
  reg [2:0] prio_top_num;
  reg [2:0] prio_high_num;
  reg hold;
  reg [7:0] ch_ready;
  reg [7:0] ch_active;
  reg finish;
  wire ch_go_out;
  wire [2:0] ch_num;
  wire ch_last;

  // DUT instantiation
  dma_axi64_core0_arbiter #(
    // .CH_LAST()
  ) dut (
    .clk(clk),
    .reset(reset),
    .enable(enable),
    .joint_mode(joint_mode),
    .page_cross(page_cross),
    .joint_req(joint_req),
    .prio_top(prio_top),
    .prio_high(prio_high),
    .prio_top_num(prio_top_num),
    .prio_high_num(prio_high_num),
    .hold(hold),
    .ch_ready(ch_ready),
    .ch_active(ch_active),
    .finish(finish),
    .ch_go_out(ch_go_out),
    .ch_num(ch_num),
    .ch_last(ch_last)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    enable = '0;
    joint_mode = '0;
    page_cross = '0;
    joint_req = '0;
    prio_top = '0;
    prio_high = '0;
    prio_top_num = '0;
    prio_high_num = '0;
    hold = '0;
    ch_ready = '0;
    ch_active = '0;
    finish = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_arbiter compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_arbiter");
    $finish;
  end

endmodule
