#!/usr/bin/env bash
# Compile script for round_robin_arbiter testbench
# Generated by blockify generate_tb.py
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SLANG="${SLANG:-$ROOT_DIR/tools/bin/slang}"

# Verify slang exists
if [ ! -x "$SLANG" ]; then
    echo "ERROR: slang not found at $SLANG"
    echo "Run src/scripts/setup_slang.sh first"
    exit 1
fi

echo "Compiling: round_robin_arbiter testbench"
"$SLANG" \
  "$SCRIPT_DIR/../../../../import/round_robin_arbiter/round_robin_arbiter.v" \
  "$SCRIPT_DIR/tb_round_robin_arbiter.v" \
  -I "$SCRIPT_DIR/../../../../import/round_robin_arbiter" \
  --allow-use-before-declare \
  --lint-only \
  --timescale "1ns/1ps"

echo "PASS: round_robin_arbiter testbench compiled successfully"