// Auto-generated testbench for round_robin_arbiter
// Source: round_robin_arbiter.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_round_robin_arbiter;

  reg rst_an;
  reg clk;
  reg [3:0] req;
  wire [3:0] grant;

  // DUT instantiation
  round_robin_arbiter dut (
    .rst_an(rst_an),
    .clk(clk),
    .req(req),
    .grant(grant)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    req = '0;
    rst_an = 1'b0;  // active-low reset asserted

    // Wait for reset
    #100;

    rst_an = 1'b1;  // release active-low reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_round_robin_arbiter compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_round_robin_arbiter");
    $finish;
  end

endmodule
