// Auto-generated testbench for prgen_delay
// Source: prgen_delay.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_prgen_delay;

  reg clk;
  reg reset;
  reg din;
  wire dout;

  // DUT instantiation
  prgen_delay #(
    // .DELAY()
  ) dut (
    .clk(clk),
    .reset(reset),
    .din(din),
    .dout(dout)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    din = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_prgen_delay compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_prgen_delay");
    $finish;
  end

endmodule
