// Auto-generated testbench for dma_axi32_core0_ch_periph_mux
// Source: dma_axi32_core0_ch_periph_mux.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_ch_periph_mux;

  reg clk;
  reg reset;
  reg clken;
  reg [30:0] periph_req;
  wire [30:0] periph_clr;
  wire periph_ready;
  reg [4:0] periph_num;
  reg clr_valid;
  reg clr;

  // DUT instantiation
  dma_axi32_core0_ch_periph_mux dut (
    .clk(clk),
    .reset(reset),
    .clken(clken),
    .periph_req(periph_req),
    .periph_clr(periph_clr),
    .periph_ready(periph_ready),
    .periph_num(periph_num),
    .clr_valid(clr_valid),
    .clr(clr)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  // Clock generation: clken
  initial clken = 1'b0;
  always #5 clken = ~clken;

  initial begin
    periph_req = '0;
    periph_num = '0;
    clr_valid = '0;
    clr = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_ch_periph_mux compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_ch_periph_mux");
    $finish;
  end

endmodule
