// Auto-generated testbench for dma_axi64_core0_ch_empty
// Source: dma_axi64_core0_ch_empty.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_ch_empty;

  reg clk;
  reg reset;
  reg scan_en;
  reg pclk;
  reg clken;
  reg pclken;
  reg psel;
  reg penable;
  reg [7:0] paddr;
  reg pwrite;
  reg [31:0] pwdata;
  wire [31:0] prdata;
  wire pslverr;
  reg [30:0] periph_tx_req;
  wire [30:0] periph_tx_clr;
  reg [30:0] periph_rx_req;
  wire [30:0] periph_rx_clr;
  reg rd_cmd_split;
  reg rd_cmd_line;
  reg rd_clr_line;
  reg rd_clr;
  reg rd_clr_load;
  reg rd_slverr;
  reg rd_decerr;
  reg wr_cmd_split;
  reg wr_cmd_pending;
  reg wr_clr_line;
  reg wr_clr;
  reg wr_clr_last;
  reg wr_slverr;
  reg wr_decerr;
  reg load_wr;
  reg [1:0] load_wr_cycle;
  reg [63:0] load_wdata;
  wire load_req_in_prog;
  wire int_all_proc;
  reg ch_start;
  wire idle;
  wire ch_active;
  wire ch_rd_active;
  wire ch_wr_active;
  wire wr_last_cmd;
  wire rd_line_cmd;
  wire wr_line_cmd;
  wire rd_go_next_line;
  wire wr_go_next_line;
  wire rd_ready;
  reg rd_burst_start;
  wire [31:0] rd_burst_addr;
  wire [7:0] rd_burst_size;
  wire rd_tokens;
  wire rd_port_num;
  wire rd_periph_delay;
  wire rd_clr_valid;
  reg rd_transfer;
  reg [3:0] rd_transfer_size;
  wire rd_clr_stall;
  wire wr_ready;
  reg wr_burst_start;
  wire [31:0] wr_burst_addr;
  wire [7:0] wr_burst_size;
  wire wr_tokens;
  wire wr_port_num;
  wire wr_periph_delay;
  wire wr_clr_valid;
  reg wr_transfer;
  reg [3:0] wr_transfer_size;
  reg [3:0] wr_next_size;
  wire wr_clr_stall;
  wire wr_incr;
  reg timeout_aw;
  reg timeout_w;
  reg timeout_ar;
  reg wdt_timeout;
  reg fifo_wr;
  reg [63:0] fifo_wdata;
  reg [3:0] fifo_wsize;
  reg fifo_rd;
  reg [3:0] fifo_rsize;
  wire fifo_rd_valid;
  wire [63:0] fifo_rdata;
  wire fifo_wr_ready;
  reg joint_mode;
  reg joint_remote;
  reg rd_page_cross;
  reg wr_page_cross;
  wire joint_in_prog;
  wire joint_not_in_prog;
  wire joint_mux_in_prog;
  wire joint_req;

  // DUT instantiation
  dma_axi64_core0_ch_empty dut (
    .clk(clk),
    .reset(reset),
    .scan_en(scan_en),
    .pclk(pclk),
    .clken(clken),
    .pclken(pclken),
    .psel(psel),
    .penable(penable),
    .paddr(paddr),
    .pwrite(pwrite),
    .pwdata(pwdata),
    .prdata(prdata),
    .pslverr(pslverr),
    .periph_tx_req(periph_tx_req),
    .periph_tx_clr(periph_tx_clr),
    .periph_rx_req(periph_rx_req),
    .periph_rx_clr(periph_rx_clr),
    .rd_cmd_split(rd_cmd_split),
    .rd_cmd_line(rd_cmd_line),
    .rd_clr_line(rd_clr_line),
    .rd_clr(rd_clr),
    .rd_clr_load(rd_clr_load),
    .rd_slverr(rd_slverr),
    .rd_decerr(rd_decerr),
    .wr_cmd_split(wr_cmd_split),
    .wr_cmd_pending(wr_cmd_pending),
    .wr_clr_line(wr_clr_line),
    .wr_clr(wr_clr),
    .wr_clr_last(wr_clr_last),
    .wr_slverr(wr_slverr),
    .wr_decerr(wr_decerr),
    .load_wr(load_wr),
    .load_wr_cycle(load_wr_cycle),
    .load_wdata(load_wdata),
    .load_req_in_prog(load_req_in_prog),
    .int_all_proc(int_all_proc),
    .ch_start(ch_start),
    .idle(idle),
    .ch_active(ch_active),
    .ch_rd_active(ch_rd_active),
    .ch_wr_active(ch_wr_active),
    .wr_last_cmd(wr_last_cmd),
    .rd_line_cmd(rd_line_cmd),
    .wr_line_cmd(wr_line_cmd),
    .rd_go_next_line(rd_go_next_line),
    .wr_go_next_line(wr_go_next_line),
    .rd_ready(rd_ready),
    .rd_burst_start(rd_burst_start),
    .rd_burst_addr(rd_burst_addr),
    .rd_burst_size(rd_burst_size),
    .rd_tokens(rd_tokens),
    .rd_port_num(rd_port_num),
    .rd_periph_delay(rd_periph_delay),
    .rd_clr_valid(rd_clr_valid),
    .rd_transfer(rd_transfer),
    .rd_transfer_size(rd_transfer_size),
    .rd_clr_stall(rd_clr_stall),
    .wr_ready(wr_ready),
    .wr_burst_start(wr_burst_start),
    .wr_burst_addr(wr_burst_addr),
    .wr_burst_size(wr_burst_size),
    .wr_tokens(wr_tokens),
    .wr_port_num(wr_port_num),
    .wr_periph_delay(wr_periph_delay),
    .wr_clr_valid(wr_clr_valid),
    .wr_transfer(wr_transfer),
    .wr_transfer_size(wr_transfer_size),
    .wr_next_size(wr_next_size),
    .wr_clr_stall(wr_clr_stall),
    .wr_incr(wr_incr),
    .timeout_aw(timeout_aw),
    .timeout_w(timeout_w),
    .timeout_ar(timeout_ar),
    .wdt_timeout(wdt_timeout),
    .fifo_wr(fifo_wr),
    .fifo_wdata(fifo_wdata),
    .fifo_wsize(fifo_wsize),
    .fifo_rd(fifo_rd),
    .fifo_rsize(fifo_rsize),
    .fifo_rd_valid(fifo_rd_valid),
    .fifo_rdata(fifo_rdata),
    .fifo_wr_ready(fifo_wr_ready),
    .joint_mode(joint_mode),
    .joint_remote(joint_remote),
    .rd_page_cross(rd_page_cross),
    .wr_page_cross(wr_page_cross),
    .joint_in_prog(joint_in_prog),
    .joint_not_in_prog(joint_not_in_prog),
    .joint_mux_in_prog(joint_mux_in_prog),
    .joint_req(joint_req)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  // Clock generation: pclk
  initial pclk = 1'b0;
  always #5 pclk = ~pclk;

  // Clock generation: clken
  initial clken = 1'b0;
  always #5 clken = ~clken;

  // Clock generation: pclken
  initial pclken = 1'b0;
  always #5 pclken = ~pclken;

  initial begin
    scan_en = '0;
    psel = '0;
    penable = '0;
    paddr = '0;
    pwrite = '0;
    pwdata = '0;
    periph_tx_req = '0;
    periph_rx_req = '0;
    rd_cmd_split = '0;
    rd_cmd_line = '0;
    rd_clr_line = '0;
    rd_clr = '0;
    rd_clr_load = '0;
    rd_slverr = '0;
    rd_decerr = '0;
    wr_cmd_split = '0;
    wr_cmd_pending = '0;
    wr_clr_line = '0;
    wr_clr = '0;
    wr_clr_last = '0;
    wr_slverr = '0;
    wr_decerr = '0;
    load_wr = '0;
    load_wr_cycle = '0;
    load_wdata = '0;
    ch_start = '0;
    rd_transfer = '0;
    rd_transfer_size = '0;
    wr_transfer = '0;
    wr_transfer_size = '0;
    wr_next_size = '0;
    timeout_aw = '0;
    timeout_w = '0;
    timeout_ar = '0;
    wdt_timeout = '0;
    fifo_wr = '0;
    fifo_wdata = '0;
    fifo_wsize = '0;
    fifo_rd = '0;
    fifo_rsize = '0;
    joint_mode = '0;
    joint_remote = '0;
    rd_page_cross = '0;
    wr_page_cross = '0;
    reset = 1'b1;  // active-high reset asserted
    rd_burst_start = 1'b1;  // active-high reset asserted
    wr_burst_start = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    rd_burst_start = 1'b0;  // release active-high reset
    wr_burst_start = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_ch_empty compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_ch_empty");
    $finish;
  end

endmodule
