// Auto-generated testbench for dma_axi64_core0_channels_apb_mux
// Source: dma_axi64_core0_channels_apb_mux.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_channels_apb_mux;

  reg clk;
  reg reset;
  reg pclken;
  reg psel;
  reg penable;
  reg [2:0] paddr;
  wire [31:0] prdata;
  wire pslverr;
  wire [7:0] ch_psel;
  reg [255:0] ch_prdata;
  reg [7:0] ch_pslverr;

  // DUT instantiation
  dma_axi64_core0_channels_apb_mux dut (
    .clk(clk),
    .reset(reset),
    .pclken(pclken),
    .psel(psel),
    .penable(penable),
    .paddr(paddr),
    .prdata(prdata),
    .pslverr(pslverr),
    .ch_psel(ch_psel),
    .ch_prdata(ch_prdata),
    .ch_pslverr(ch_pslverr)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  // Clock generation: pclken
  initial pclken = 1'b0;
  always #5 pclken = ~pclken;

  initial begin
    psel = '0;
    penable = '0;
    paddr = '0;
    ch_prdata = '0;
    ch_pslverr = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_channels_apb_mux compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_channels_apb_mux");
    $finish;
  end

endmodule
