// Auto-generated testbench for dma_axi32_core0_axim_wr
// Source: dma_axi32_core0_axim_wr.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_axim_wr;

  reg clk;
  reg reset;
  reg wr_cmd_port;
  reg wr_last_cmd;
  reg wr_line_cmd;
  reg [2:0] wr_ch_num;
  reg wr_burst_start;
  reg [31:0] wr_burst_addr;
  reg [6:0] wr_burst_size;
  wire wr_cmd_pending;
  wire wr_cmd_split;
  wire [2:0] wr_cmd_num;
  reg rd_transfer;
  reg [2:0] rd_transfer_size;
  wire ch_fifo_rd;
  reg [31:0] ch_fifo_rdata;
  reg ch_fifo_rd_valid;
  wire [2:0] ch_fifo_rsize;
  reg ch_fifo_wr_ready;
  wire [2:0] ch_fifo_rd_num;
  wire [2:0] wr_transfer_num;
  wire wr_transfer;
  wire [2:0] wr_transfer_size;
  wire [2:0] wr_next_size;
  wire wr_cmd_full;
  wire wr_clr_line;
  wire [2:0] wr_clr_line_num;
  wire wr_slverr;
  wire wr_decerr;
  wire wr_clr;
  wire wr_clr_last;
  wire [2:0] wr_ch_num_resp;
  wire page_cross;
  wire [31:0] AWADDR;
  wire AWPORT;
  wire AWLEN;
  wire [1:0] AWSIZE;
  wire AWVALID;
  reg AWREADY;
  wire [31:0] WDATA;
  wire [3:0] WSTRB;
  wire WLAST;
  wire WVALID;
  reg WREADY;
  reg [1:0] BRESP;
  reg BVALID;
  wire BREADY;
  reg joint_req;
  wire joint_stall;
  wire axim_timeout_aw;
  wire axim_timeout_w;
  wire [2:0] axim_timeout_num_aw;
  wire [2:0] axim_timeout_num_w;

  // DUT instantiation
  dma_axi32_core0_axim_wr dut (
    .clk(clk),
    .reset(reset),
    .wr_cmd_port(wr_cmd_port),
    .wr_last_cmd(wr_last_cmd),
    .wr_line_cmd(wr_line_cmd),
    .wr_ch_num(wr_ch_num),
    .wr_burst_start(wr_burst_start),
    .wr_burst_addr(wr_burst_addr),
    .wr_burst_size(wr_burst_size),
    .wr_cmd_pending(wr_cmd_pending),
    .wr_cmd_split(wr_cmd_split),
    .wr_cmd_num(wr_cmd_num),
    .rd_transfer(rd_transfer),
    .rd_transfer_size(rd_transfer_size),
    .ch_fifo_rd(ch_fifo_rd),
    .ch_fifo_rdata(ch_fifo_rdata),
    .ch_fifo_rd_valid(ch_fifo_rd_valid),
    .ch_fifo_rsize(ch_fifo_rsize),
    .ch_fifo_wr_ready(ch_fifo_wr_ready),
    .ch_fifo_rd_num(ch_fifo_rd_num),
    .wr_transfer_num(wr_transfer_num),
    .wr_transfer(wr_transfer),
    .wr_transfer_size(wr_transfer_size),
    .wr_next_size(wr_next_size),
    .wr_cmd_full(wr_cmd_full),
    .wr_clr_line(wr_clr_line),
    .wr_clr_line_num(wr_clr_line_num),
    .wr_slverr(wr_slverr),
    .wr_decerr(wr_decerr),
    .wr_clr(wr_clr),
    .wr_clr_last(wr_clr_last),
    .wr_ch_num_resp(wr_ch_num_resp),
    .page_cross(page_cross),
    .AWADDR(AWADDR),
    .AWPORT(AWPORT),
    .AWLEN(AWLEN),
    .AWSIZE(AWSIZE),
    .AWVALID(AWVALID),
    .AWREADY(AWREADY),
    .WDATA(WDATA),
    .WSTRB(WSTRB),
    .WLAST(WLAST),
    .WVALID(WVALID),
    .WREADY(WREADY),
    .BRESP(BRESP),
    .BVALID(BVALID),
    .BREADY(BREADY),
    .joint_req(joint_req),
    .joint_stall(joint_stall),
    .axim_timeout_aw(axim_timeout_aw),
    .axim_timeout_w(axim_timeout_w),
    .axim_timeout_num_aw(axim_timeout_num_aw),
    .axim_timeout_num_w(axim_timeout_num_w)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    wr_cmd_port = '0;
    wr_last_cmd = '0;
    wr_line_cmd = '0;
    wr_ch_num = '0;
    rd_transfer = '0;
    rd_transfer_size = '0;
    ch_fifo_rdata = '0;
    ch_fifo_rd_valid = '0;
    ch_fifo_wr_ready = '0;
    AWREADY = '0;
    WREADY = '0;
    BRESP = '0;
    BVALID = '0;
    joint_req = '0;
    reset = 1'b1;  // active-high reset asserted
    wr_burst_start = 1'b1;  // active-high reset asserted
    wr_burst_addr = 1'b1;  // active-high reset asserted
    wr_burst_size = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    wr_burst_start = 1'b0;  // release active-high reset
    wr_burst_addr = 1'b0;  // release active-high reset
    wr_burst_size = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_axim_wr compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_axim_wr");
    $finish;
  end

endmodule
