// Auto-generated testbench for dma_axi64_dual_core
// Source: dma_axi64_dual_core.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_dual_core;

  reg clk;
  reg reset;
  reg scan_en;
  wire idle;
  wire INT;
  reg [30:0] periph_tx_req;
  wire [30:0] periph_tx_clr;
  reg [30:0] periph_rx_req;
  wire [30:0] periph_rx_clr;
  reg pclken;
  reg psel;
  reg penable;
  reg [12:0] paddr;
  reg pwrite;
  reg [31:0] pwdata;
  wire [31:0] prdata;
  wire pslverr;
  wire pready;
  wire rd_port_num0;
  wire wr_port_num0;
  wire rd_port_num1;
  wire wr_port_num1;
  wire M0_AWID;
  wire [31:0] M0_AWADDR;
  wire M0_AWLEN;
  wire M0_AWSIZE;
  wire M0_AWVALID;
  reg M0_AWREADY;
  wire M0_WID;
  wire [63:0] M0_WDATA;
  wire [7:0] M0_WSTRB;
  wire M0_WLAST;
  wire M0_WVALID;
  reg M0_WREADY;
  reg M0_BID;
  reg [1:0] M0_BRESP;
  reg M0_BVALID;
  wire M0_BREADY;
  wire M0_ARID;
  wire [31:0] M0_ARADDR;
  wire M0_ARLEN;
  wire M0_ARSIZE;
  wire M0_ARVALID;
  reg M0_ARREADY;
  reg M0_RID;
  reg [63:0] M0_RDATA;
  reg [1:0] M0_RRESP;
  reg M0_RLAST;
  reg M0_RVALID;
  wire M0_RREADY;

  // DUT instantiation
  dma_axi64_dual_core dut (
    .clk(clk),
    .reset(reset),
    .scan_en(scan_en),
    .idle(idle),
    .INT(INT),
    .periph_tx_req(periph_tx_req),
    .periph_tx_clr(periph_tx_clr),
    .periph_rx_req(periph_rx_req),
    .periph_rx_clr(periph_rx_clr),
    .pclken(pclken),
    .psel(psel),
    .penable(penable),
    .paddr(paddr),
    .pwrite(pwrite),
    .pwdata(pwdata),
    .prdata(prdata),
    .pslverr(pslverr),
    .pready(pready),
    .rd_port_num0(rd_port_num0),
    .wr_port_num0(wr_port_num0),
    .rd_port_num1(rd_port_num1),
    .wr_port_num1(wr_port_num1),
    .M0_AWID(M0_AWID),
    .M0_AWADDR(M0_AWADDR),
    .M0_AWLEN(M0_AWLEN),
    .M0_AWSIZE(M0_AWSIZE),
    .M0_AWVALID(M0_AWVALID),
    .M0_AWREADY(M0_AWREADY),
    .M0_WID(M0_WID),
    .M0_WDATA(M0_WDATA),
    .M0_WSTRB(M0_WSTRB),
    .M0_WLAST(M0_WLAST),
    .M0_WVALID(M0_WVALID),
    .M0_WREADY(M0_WREADY),
    .M0_BID(M0_BID),
    .M0_BRESP(M0_BRESP),
    .M0_BVALID(M0_BVALID),
    .M0_BREADY(M0_BREADY),
    .M0_ARID(M0_ARID),
    .M0_ARADDR(M0_ARADDR),
    .M0_ARLEN(M0_ARLEN),
    .M0_ARSIZE(M0_ARSIZE),
    .M0_ARVALID(M0_ARVALID),
    .M0_ARREADY(M0_ARREADY),
    .M0_RID(M0_RID),
    .M0_RDATA(M0_RDATA),
    .M0_RRESP(M0_RRESP),
    .M0_RLAST(M0_RLAST),
    .M0_RVALID(M0_RVALID),
    .M0_RREADY(M0_RREADY)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  // Clock generation: pclken
  initial pclken = 1'b0;
  always #5 pclken = ~pclken;

  initial begin
    scan_en = '0;
    periph_tx_req = '0;
    periph_rx_req = '0;
    psel = '0;
    penable = '0;
    paddr = '0;
    pwrite = '0;
    pwdata = '0;
    M0_AWREADY = '0;
    M0_WREADY = '0;
    M0_BID = '0;
    M0_BRESP = '0;
    M0_BVALID = '0;
    M0_ARREADY = '0;
    M0_RID = '0;
    M0_RDATA = '0;
    M0_RRESP = '0;
    M0_RLAST = '0;
    M0_RVALID = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_dual_core compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_dual_core");
    $finish;
  end

endmodule
