// Auto-generated testbench for dma_axi64_apb_mux
// Source: dma_axi64_apb_mux.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_apb_mux;

  reg clk;
  reg reset;
  reg pclken;
  reg psel;
  reg penable;
  reg pwrite;
  reg [1:0] paddr;
  wire [31:0] prdata;
  wire pslverr;
  wire pready;
  wire psel0;
  reg [31:0] prdata0;
  reg pslverr0;
  wire psel1;
  reg [31:0] prdata1;
  reg pslverr1;
  wire psel_reg;
  reg [31:0] prdata_reg;
  reg pslverr_reg;

  // DUT instantiation
  dma_axi64_apb_mux dut (
    .clk(clk),
    .reset(reset),
    .pclken(pclken),
    .psel(psel),
    .penable(penable),
    .pwrite(pwrite),
    .paddr(paddr),
    .prdata(prdata),
    .pslverr(pslverr),
    .pready(pready),
    .psel0(psel0),
    .prdata0(prdata0),
    .pslverr0(pslverr0),
    .psel1(psel1),
    .prdata1(prdata1),
    .pslverr1(pslverr1),
    .psel_reg(psel_reg),
    .prdata_reg(prdata_reg),
    .pslverr_reg(pslverr_reg)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  // Clock generation: pclken
  initial pclken = 1'b0;
  always #5 pclken = ~pclken;

  initial begin
    psel = '0;
    penable = '0;
    pwrite = '0;
    paddr = '0;
    prdata0 = '0;
    pslverr0 = '0;
    prdata1 = '0;
    pslverr1 = '0;
    prdata_reg = '0;
    pslverr_reg = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_apb_mux compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_apb_mux");
    $finish;
  end

endmodule
