// Auto-generated testbench for dma_axi64_core0_ch_wr_slicer
// Source: dma_axi64_core0_ch_wr_slicer.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_ch_wr_slicer;

  reg clk;
  reg reset;
  reg ch_update;
  reg rd_clr_line;
  reg fifo_wr;
  reg [63:0] fifo_wdata;
  reg [3:0] fifo_wsize;
  reg [2:0] wr_align;
  reg [4:0] wr_ptr;
  reg rd_incr;
  reg [1:0] end_swap;
  wire slice_wr;
  wire slice_wr_fifo;
  wire [4:0] slice_wr_ptr;
  wire [7:0] slice_bsel;
  wire [63:0] slice_wdata;
  wire [3:0] slice_wsize;

  // DUT instantiation
  dma_axi64_core0_ch_wr_slicer dut (
    .clk(clk),
    .reset(reset),
    .ch_update(ch_update),
    .rd_clr_line(rd_clr_line),
    .fifo_wr(fifo_wr),
    .fifo_wdata(fifo_wdata),
    .fifo_wsize(fifo_wsize),
    .wr_align(wr_align),
    .wr_ptr(wr_ptr),
    .rd_incr(rd_incr),
    .end_swap(end_swap),
    .slice_wr(slice_wr),
    .slice_wr_fifo(slice_wr_fifo),
    .slice_wr_ptr(slice_wr_ptr),
    .slice_bsel(slice_bsel),
    .slice_wdata(slice_wdata),
    .slice_wsize(slice_wsize)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    ch_update = '0;
    rd_clr_line = '0;
    fifo_wr = '0;
    fifo_wdata = '0;
    fifo_wsize = '0;
    wr_align = '0;
    wr_ptr = '0;
    rd_incr = '0;
    end_swap = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_ch_wr_slicer compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_ch_wr_slicer");
    $finish;
  end

endmodule
