// Auto-generated testbench for prgen_joint_stall
// Source: prgen_joint_stall.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_prgen_joint_stall;

  reg clk;
  reg reset;
  reg joint_req_out;
  reg rd_transfer;
  reg rd_transfer_size;
  reg ch_fifo_rd;
  reg [2:0] data_fullness_pre;
  reg HOLD;
  wire joint_fifo_rd_valid;
  wire rd_transfer_size_joint;
  wire rd_transfer_full;
  wire joint_stall;

  // DUT instantiation
  prgen_joint_stall #(
    // .SIZE_BITS()
  ) dut (
    .clk(clk),
    .reset(reset),
    .joint_req_out(joint_req_out),
    .rd_transfer(rd_transfer),
    .rd_transfer_size(rd_transfer_size),
    .ch_fifo_rd(ch_fifo_rd),
    .data_fullness_pre(data_fullness_pre),
    .HOLD(HOLD),
    .joint_fifo_rd_valid(joint_fifo_rd_valid),
    .rd_transfer_size_joint(rd_transfer_size_joint),
    .rd_transfer_full(rd_transfer_full),
    .joint_stall(joint_stall)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    joint_req_out = '0;
    rd_transfer = '0;
    rd_transfer_size = '0;
    ch_fifo_rd = '0;
    data_fullness_pre = '0;
    HOLD = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_prgen_joint_stall compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_prgen_joint_stall");
    $finish;
  end

endmodule
