// Auto-generated testbench for prgen_mux8
// Source: prgen_mux8.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_prgen_mux8;

  reg [2:0] sel;
  reg [63:0] ch_x;
  wire [7:0] x;

  // DUT instantiation
  prgen_mux8 #(
    // .WIDTH()
  ) dut (
    .sel(sel),
    .ch_x(ch_x),
    .x(x)
  );

  initial begin
    sel = '0;
    ch_x = '0;

    // Wait for reset
    #100;


    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_prgen_mux8 compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_prgen_mux8");
    $finish;
  end

endmodule
