#!/usr/bin/env python3
"""
generate_tb.py - Generates a minimal compile-check testbench for a Verilog/SystemVerilog module.

Usage:
    python3 generate_tb.py <rtl_file> --slang <slang_path> --output-dir <dir> [--include-dir <dir>] [--defines KEY=VAL ...]

The generated testbench:
  - Instantiates the module with all ports connected
  - Drives clocks and resets
  - Provides a compile_cmd.sh script for slang compilation
  - Reports compilation status
"""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path


def run_slang_ast(slang_path, rtl_file, include_dirs=None, defines=None, extra_args=None):
    """Run slang to get AST JSON for a file."""
    import tempfile
    fd, ast_file = tempfile.mkstemp(suffix=".json")

    cmd = [slang_path, str(rtl_file), "--ast-json", ast_file, "--allow-use-before-declare"]

    if include_dirs:
        for inc in include_dirs:
            cmd.extend(["-I", str(inc)])

    if defines:
        for d in defines:
            cmd.extend(["-D", d])

    if extra_args:
        cmd.extend(extra_args)

    result = subprocess.run(cmd, capture_output=True, text=True)
    os.close(fd)

    if os.path.exists(ast_file):
        with open(ast_file) as f:
            ast = json.load(f)
        os.unlink(ast_file)
        return ast, result.stdout + result.stderr, result.returncode
    else:
        return None, result.stdout + result.stderr, result.returncode


def extract_modules_from_ast(ast):
    """Extract module information from slang AST JSON."""
    modules = []
    design = ast.get("design", {})

    for member in design.get("members", []):
        if member.get("kind") != "Instance":
            continue

        body = member.get("body", {})
        if body.get("kind") != "InstanceBody":
            continue

        module = {
            "name": body["name"],
            "ports": [],
            "parameters": [],
            "variables": [],
            "nets": [],
            "procedural_blocks": [],
        }

        for m in body.get("members", []):
            kind = m.get("kind", "")
            name = m.get("name", "")

            if kind == "Port":
                module["ports"].append({
                    "name": name,
                    "direction": m.get("direction", ""),
                    "type": m.get("type", ""),
                })
            elif kind == "Parameter":
                module["parameters"].append({
                    "name": name,
                    "type": m.get("type", ""),
                    "value": m.get("value", ""),
                })
            elif kind == "Variable":
                module["variables"].append({
                    "name": name,
                    "type": m.get("type", ""),
                })
            elif kind == "Net":
                module["nets"].append({
                    "name": name,
                    "type": m.get("type", ""),
                })
            elif kind == "ProceduralBlock":
                module["procedural_blocks"].append({
                    "kind": m.get("procedureKind", ""),
                })

        modules.append(module)

    return modules


def parse_width_from_type(type_str):
    """Parse the bit width from a Verilog type string like 'logic[3:0]' or 'reg[7:0]'."""
    match = re.search(r'\[(\d+):(\d+)\]', type_str)
    if match:
        high = int(match.group(1))
        low = int(match.group(2))
        return abs(high - low) + 1
    return 1


def generate_testbench(module, rtl_filename):
    """Generate a testbench for a module."""
    mod_name = module["name"]
    tb_name = f"tb_{mod_name}"

    lines = []
    lines.append(f"// Auto-generated testbench for {mod_name}")
    lines.append(f"// Source: {rtl_filename}")
    lines.append(f"// Generated by blockify generate_tb.py")
    lines.append(f"// Purpose: Compile-check and basic instantiation test")
    lines.append(f"")
    lines.append(f"`timescale 1ns/1ps")
    lines.append(f"")
    lines.append(f"module {tb_name};")
    lines.append(f"")

    # Declare signals
    clk_signals = []
    rst_signals = []
    input_signals = []
    output_signals = []

    for port in module["ports"]:
        name = port["name"]
        ptype = port["type"]
        direction = port["direction"]
        width = parse_width_from_type(ptype)
        width_str = f"[{width-1}:0] " if width > 1 else ""

        if direction == "In":
            # Detect clocks and resets
            name_lower = name.lower()
            if any(ck in name_lower for ck in ["clk", "clock"]):
                lines.append(f"  reg {width_str}{name};")
                clk_signals.append(name)
            elif any(rs in name_lower for rs in ["rst", "reset", "rstn", "rst_n", "rst_an"]):
                lines.append(f"  reg {width_str}{name};")
                rst_signals.append((name, name_lower))
            else:
                lines.append(f"  reg {width_str}{name};")
                input_signals.append(name)
        elif direction == "Out":
            lines.append(f"  wire {width_str}{name};")
            output_signals.append(name)
        elif direction == "InOut":
            lines.append(f"  wire {width_str}{name};")
            output_signals.append(name)

    lines.append(f"")

    # Instantiate DUT
    lines.append(f"  // DUT instantiation")

    # Handle parameters
    if module["parameters"]:
        param_list = ", ".join(
            f".{p['name']}({p['name']})" for p in module["parameters"]
        )
        lines.append(f"  {mod_name} #(")
        for i, p in enumerate(module["parameters"]):
            comma = "," if i < len(module["parameters"]) - 1 else ""
            # Use default value if available
            lines.append(f"    // .{p['name']}(){comma}")
        lines.append(f"  ) dut (")
    else:
        lines.append(f"  {mod_name} dut (")

    for i, port in enumerate(module["ports"]):
        comma = "," if i < len(module["ports"]) - 1 else ""
        lines.append(f"    .{port['name']}({port['name']}){comma}")
    lines.append(f"  );")
    lines.append(f"")

    # Clock generation
    for clk in clk_signals:
        lines.append(f"  // Clock generation: {clk}")
        lines.append(f"  initial {clk} = 1'b0;")
        lines.append(f"  always #5 {clk} = ~{clk};")
        lines.append(f"")

    # Reset and test sequence
    lines.append(f"  initial begin")

    # Initialize inputs
    for name in input_signals:
        lines.append(f"    {name} = '0;")

    # Handle resets
    for name, name_lower in rst_signals:
        # Detect active-low resets
        if any(x in name_lower for x in ["_n", "_an", "rstn", "resetn", "rst_n"]):
            lines.append(f"    {name} = 1'b0;  // active-low reset asserted")
        else:
            lines.append(f"    {name} = 1'b1;  // active-high reset asserted")

    lines.append(f"")
    lines.append(f"    // Wait for reset")
    lines.append(f"    #100;")
    lines.append(f"")

    # Deassert resets
    for name, name_lower in rst_signals:
        if any(x in name_lower for x in ["_n", "_an", "rstn", "resetn", "rst_n"]):
            lines.append(f"    {name} = 1'b1;  // release active-low reset")
        else:
            lines.append(f"    {name} = 1'b0;  // release active-high reset")

    lines.append(f"")
    lines.append(f"    // Basic test: wait a few cycles")
    lines.append(f"    #200;")
    lines.append(f"")
    lines.append(f"    $display(\"PASS: {tb_name} compile and instantiation test\");")
    lines.append(f"    $finish;")
    lines.append(f"  end")
    lines.append(f"")
    lines.append(f"  // Timeout watchdog")
    lines.append(f"  initial begin")
    lines.append(f"    #10000;")
    lines.append(f"    $display(\"TIMEOUT: {tb_name}\");")
    lines.append(f"    $finish;")
    lines.append(f"  end")
    lines.append(f"")
    lines.append(f"endmodule")
    lines.append(f"")

    return "\n".join(lines)


def generate_compile_script(mod_name, rtl_file, tb_file, slang_path,
                            include_dirs=None, defines=None):
    """Generate a shell script to compile the testbench with slang."""
    lines = []
    lines.append("#!/usr/bin/env bash")
    lines.append(f"# Compile script for {mod_name} testbench")
    lines.append(f"# Generated by blockify generate_tb.py")
    lines.append("set -euo pipefail")
    lines.append("")
    lines.append('SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"')
    lines.append('ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"')
    lines.append(f'SLANG="${{SLANG:-$ROOT_DIR/tools/bin/slang}}"')
    lines.append("")
    lines.append("# Verify slang exists")
    lines.append('if [ ! -x "$SLANG" ]; then')
    lines.append('    echo "ERROR: slang not found at $SLANG"')
    lines.append('    echo "Run src/scripts/setup_slang.sh first"')
    lines.append("    exit 1")
    lines.append("fi")
    lines.append("")

    # Build the slang command
    cmd_parts = ['"$SLANG"']

    # RTL file - use path relative to script dir
    rtl_rel = os.path.relpath(rtl_file, os.path.dirname(tb_file))
    cmd_parts.append(f'"$SCRIPT_DIR/{rtl_rel}"')

    # TB file
    tb_basename = os.path.basename(tb_file)
    cmd_parts.append(f'"$SCRIPT_DIR/{tb_basename}"')

    if include_dirs:
        for inc in include_dirs:
            inc_rel = os.path.relpath(inc, os.path.dirname(tb_file))
            cmd_parts.append(f'-I "$SCRIPT_DIR/{inc_rel}"')

    if defines:
        for d in defines:
            cmd_parts.append(f"-D {d}")

    cmd_parts.append("--allow-use-before-declare")
    cmd_parts.append("--lint-only")
    cmd_parts.append('--timescale "1ns/1ps"')

    lines.append("echo \"Compiling: " + mod_name + " testbench\"")
    lines.append(" \\\n  ".join(cmd_parts))
    lines.append("")
    lines.append(f'echo "PASS: {mod_name} testbench compiled successfully"')

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate testbench for Verilog module")
    parser.add_argument("rtl_file", help="Path to Verilog/SystemVerilog source file")
    parser.add_argument("--slang", required=True, help="Path to slang binary")
    parser.add_argument("--output-dir", required=True, help="Output directory for testbench")
    parser.add_argument("--include-dir", "-I", action="append", default=[], help="Include directories")
    parser.add_argument("--define", "-D", action="append", default=[], help="Preprocessor defines")
    args = parser.parse_args()

    rtl_file = Path(args.rtl_file).resolve()
    output_dir = Path(args.output_dir).resolve()
    slang_path = Path(args.slang).resolve()

    if not rtl_file.exists():
        print(f"ERROR: RTL file not found: {rtl_file}", file=sys.stderr)
        sys.exit(1)

    if not slang_path.exists():
        print(f"ERROR: slang not found: {slang_path}", file=sys.stderr)
        sys.exit(1)

    # Get include dirs - always include the RTL file's directory
    include_dirs = [str(rtl_file.parent)] + [str(Path(d).resolve()) for d in args.include_dir]

    # Run slang to get AST
    print(f"[generate_tb] Parsing {rtl_file.name} with slang...")
    ast, output, rc = run_slang_ast(str(slang_path), str(rtl_file), include_dirs, args.define)

    if ast is None:
        print(f"[generate_tb] ERROR: slang failed to parse {rtl_file.name}")
        print(output)
        sys.exit(1)

    # Extract modules
    modules = extract_modules_from_ast(ast)

    if not modules:
        print(f"[generate_tb] WARNING: No modules found in {rtl_file.name}")
        sys.exit(0)

    # Use file stem for directory to avoid collisions when multiple files
    # define modules with the same name
    file_stem = rtl_file.stem

    for module in modules:
        mod_name = module["name"]
        tb_dir = output_dir / file_stem
        tb_dir.mkdir(parents=True, exist_ok=True)

        # Generate testbench
        tb_code = generate_testbench(module, rtl_file.name)
        tb_file = tb_dir / f"tb_{file_stem}.v"
        tb_file.write_text(tb_code)
        print(f"[generate_tb] Generated: {tb_file}")

        # Generate compile script
        compile_script = generate_compile_script(
            mod_name, str(rtl_file), str(tb_file),
            str(slang_path), include_dirs, args.define
        )
        compile_file = tb_dir / "compile_cmd.sh"
        compile_file.write_text(compile_script)
        os.chmod(str(compile_file), 0o755)
        print(f"[generate_tb] Generated: {compile_file}")

        # Test compilation
        print(f"[generate_tb] Compiling {mod_name} testbench...")
        slang_cmd = [
            str(slang_path), str(rtl_file), str(tb_file),
            "--allow-use-before-declare", "--lint-only",
            "--timescale", "1ns/1ps",
        ]
        for inc in include_dirs:
            slang_cmd.extend(["-I", inc])
        for d in args.define:
            slang_cmd.extend(["-D", d])

        result = subprocess.run(slang_cmd, capture_output=True, text=True)
        if result.returncode == 0:
            print(f"[generate_tb] PASS: {mod_name} compiled successfully")
        else:
            print(f"[generate_tb] FAIL: {mod_name} compilation failed:")
            print(result.stdout + result.stderr)

        # Write compilation result
        result_file = tb_dir / "compile_result.txt"
        result_file.write_text(
            f"file: {rtl_file.name}\n"
            f"module: {mod_name}\n"
            f"status: {'PASS' if result.returncode == 0 else 'FAIL'}\n"
            f"slang_output:\n{result.stdout + result.stderr}\n"
        )


if __name__ == "__main__":
    main()
