// Auto-generated testbench for dma_axi32_core0_ch_remain
// Source: dma_axi32_core0_ch_remain.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_ch_remain;

  reg clk;
  reg reset;
  reg ch_update;
  reg wr_outstanding;
  reg rd_outstanding;
  reg load_req_in_prog;
  reg rd_line_cmd;
  reg rd_burst_start;
  reg [6:0] rd_burst_size;
  reg rd_transfer;
  reg [2:0] rd_transfer_size;
  reg wr_clr_line;
  reg wr_burst_start;
  reg [6:0] wr_burst_size;
  reg wr_transfer;
  reg [2:0] wr_transfer_size;
  wire [5:0] rd_gap;
  wire [5:0] wr_fullness;

  // DUT instantiation
  dma_axi32_core0_ch_remain dut (
    .clk(clk),
    .reset(reset),
    .ch_update(ch_update),
    .wr_outstanding(wr_outstanding),
    .rd_outstanding(rd_outstanding),
    .load_req_in_prog(load_req_in_prog),
    .rd_line_cmd(rd_line_cmd),
    .rd_burst_start(rd_burst_start),
    .rd_burst_size(rd_burst_size),
    .rd_transfer(rd_transfer),
    .rd_transfer_size(rd_transfer_size),
    .wr_clr_line(wr_clr_line),
    .wr_burst_start(wr_burst_start),
    .wr_burst_size(wr_burst_size),
    .wr_transfer(wr_transfer),
    .wr_transfer_size(wr_transfer_size),
    .rd_gap(rd_gap),
    .wr_fullness(wr_fullness)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    ch_update = '0;
    wr_outstanding = '0;
    rd_outstanding = '0;
    load_req_in_prog = '0;
    rd_line_cmd = '0;
    rd_transfer = '0;
    rd_transfer_size = '0;
    wr_clr_line = '0;
    wr_transfer = '0;
    wr_transfer_size = '0;
    reset = 1'b1;  // active-high reset asserted
    rd_burst_start = 1'b1;  // active-high reset asserted
    rd_burst_size = 1'b1;  // active-high reset asserted
    wr_burst_start = 1'b1;  // active-high reset asserted
    wr_burst_size = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    rd_burst_start = 1'b0;  // release active-high reset
    rd_burst_size = 1'b0;  // release active-high reset
    wr_burst_start = 1'b0;  // release active-high reset
    wr_burst_size = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_ch_remain compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_ch_remain");
    $finish;
  end

endmodule
