// Auto-generated testbench for dma_axi32_core0
// Source: dma_axi32_core0.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0;

  reg clk;
  reg reset;
  reg scan_en;
  wire idle;
  wire [7:0] ch_int_all_proc;
  reg [7:0] ch_start;
  reg [30:0] periph_tx_req;
  wire [30:0] periph_tx_clr;
  reg [30:0] periph_rx_req;
  wire [30:0] periph_rx_clr;
  reg pclk;
  reg clken;
  reg pclken;
  reg psel;
  reg penable;
  reg [10:0] paddr;
  reg pwrite;
  reg [31:0] pwdata;
  wire [31:0] prdata;
  wire pslverr;
  wire rd_port_num;
  wire wr_port_num;
  reg joint_mode_in;
  reg joint_remote;
  reg rd_prio_top;
  reg rd_prio_high;
  reg [2:0] rd_prio_top_num;
  reg [2:0] rd_prio_high_num;
  reg wr_prio_top;
  reg wr_prio_high;
  reg [2:0] wr_prio_top_num;
  reg [2:0] wr_prio_high_num;
  wire [31:0] AWADDR;
  wire AWLEN;
  wire AWSIZE;
  wire AWVALID;
  reg AWREADY;
  wire [31:0] WDATA;
  wire [3:0] WSTRB;
  wire WLAST;
  wire WVALID;
  reg WREADY;
  reg [1:0] BRESP;
  reg BVALID;
  wire BREADY;
  wire [31:0] ARADDR;
  wire ARLEN;
  wire ARSIZE;
  wire ARVALID;
  reg ARREADY;
  reg [31:0] RDATA;
  reg [1:0] RRESP;
  reg RLAST;
  reg RVALID;
  wire RREADY;

  // DUT instantiation
  dma_axi32_core0 dut (
    .clk(clk),
    .reset(reset),
    .scan_en(scan_en),
    .idle(idle),
    .ch_int_all_proc(ch_int_all_proc),
    .ch_start(ch_start),
    .periph_tx_req(periph_tx_req),
    .periph_tx_clr(periph_tx_clr),
    .periph_rx_req(periph_rx_req),
    .periph_rx_clr(periph_rx_clr),
    .pclk(pclk),
    .clken(clken),
    .pclken(pclken),
    .psel(psel),
    .penable(penable),
    .paddr(paddr),
    .pwrite(pwrite),
    .pwdata(pwdata),
    .prdata(prdata),
    .pslverr(pslverr),
    .rd_port_num(rd_port_num),
    .wr_port_num(wr_port_num),
    .joint_mode_in(joint_mode_in),
    .joint_remote(joint_remote),
    .rd_prio_top(rd_prio_top),
    .rd_prio_high(rd_prio_high),
    .rd_prio_top_num(rd_prio_top_num),
    .rd_prio_high_num(rd_prio_high_num),
    .wr_prio_top(wr_prio_top),
    .wr_prio_high(wr_prio_high),
    .wr_prio_top_num(wr_prio_top_num),
    .wr_prio_high_num(wr_prio_high_num),
    .AWADDR(AWADDR),
    .AWLEN(AWLEN),
    .AWSIZE(AWSIZE),
    .AWVALID(AWVALID),
    .AWREADY(AWREADY),
    .WDATA(WDATA),
    .WSTRB(WSTRB),
    .WLAST(WLAST),
    .WVALID(WVALID),
    .WREADY(WREADY),
    .BRESP(BRESP),
    .BVALID(BVALID),
    .BREADY(BREADY),
    .ARADDR(ARADDR),
    .ARLEN(ARLEN),
    .ARSIZE(ARSIZE),
    .ARVALID(ARVALID),
    .ARREADY(ARREADY),
    .RDATA(RDATA),
    .RRESP(RRESP),
    .RLAST(RLAST),
    .RVALID(RVALID),
    .RREADY(RREADY)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  // Clock generation: pclk
  initial pclk = 1'b0;
  always #5 pclk = ~pclk;

  // Clock generation: clken
  initial clken = 1'b0;
  always #5 clken = ~clken;

  // Clock generation: pclken
  initial pclken = 1'b0;
  always #5 pclken = ~pclken;

  initial begin
    scan_en = '0;
    ch_start = '0;
    periph_tx_req = '0;
    periph_rx_req = '0;
    psel = '0;
    penable = '0;
    paddr = '0;
    pwrite = '0;
    pwdata = '0;
    joint_mode_in = '0;
    joint_remote = '0;
    rd_prio_top = '0;
    rd_prio_high = '0;
    rd_prio_top_num = '0;
    rd_prio_high_num = '0;
    wr_prio_top = '0;
    wr_prio_high = '0;
    wr_prio_top_num = '0;
    wr_prio_high_num = '0;
    AWREADY = '0;
    WREADY = '0;
    BRESP = '0;
    BVALID = '0;
    ARREADY = '0;
    RDATA = '0;
    RRESP = '0;
    RLAST = '0;
    RVALID = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0 compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0");
    $finish;
  end

endmodule
