// Auto-generated testbench for dma_axi64_core0_channels_mux
// Source: dma_axi64_core0_channels_mux.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_channels_mux;

  reg [7:0] ch_fifo_rd_valid;
  wire fifo_rd_valid;
  reg [511:0] ch_fifo_rdata;
  wire [63:0] fifo_rdata;
  reg [247:0] ch_periph_rx_clr;
  wire [30:0] periph_rx_clr;
  reg [247:0] ch_periph_tx_clr;
  wire [30:0] periph_tx_clr;
  wire [7:0] ch_rd_page_cross;
  wire [7:0] ch_wr_page_cross;
  reg rd_page_cross;
  reg wr_page_cross;
  reg timeout_aw;
  reg timeout_w;
  reg timeout_ar;
  reg [2:0] timeout_num_aw;
  reg [2:0] timeout_num_w;
  reg [2:0] timeout_num_ar;
  reg wdt_timeout;
  reg [2:0] wdt_ch_num;
  wire [7:0] ch_timeout_aw;
  wire [7:0] ch_timeout_w;
  wire [7:0] ch_timeout_ar;
  wire [7:0] ch_wdt_timeout;
  wire joint_in_prog;
  wire joint_not_in_prog;
  wire joint_mux_in_prog;
  reg [7:0] ch_joint_in_prog;
  reg [7:0] ch_joint_not_in_prog;
  reg [7:0] ch_joint_mux_in_prog;
  reg wr_cmd_pending;
  wire [7:0] ch_wr_cmd_pending;
  reg [2:0] rd_ch_num;
  reg [2:0] rd_cmd_num;
  wire load_req_in_prog;
  wire rd_line_cmd;
  wire rd_go_next_line;
  reg rd_burst_start;
  wire [31:0] rd_burst_addr;
  wire [7:0] rd_burst_size;
  wire rd_tokens;
  wire rd_cmd_port;
  wire rd_periph_delay;
  wire rd_clr_valid;
  reg rd_cmd_split;
  reg rd_cmd_line;
  wire rd_clr_stall;
  reg [7:0] ch_load_req_in_prog;
  reg [7:0] ch_rd_line_cmd;
  reg [7:0] ch_rd_go_next_line;
  wire [7:0] ch_rd_burst_start;
  reg [255:0] ch_rd_burst_addr;
  reg [63:0] ch_rd_burst_size;
  reg ch_rd_tokens;
  reg [7:0] ch_rd_port_num;
  reg ch_rd_periph_delay;
  reg [7:0] ch_rd_clr_valid;
  wire [7:0] ch_rd_cmd_split;
  wire [7:0] ch_rd_cmd_line;
  reg [7:0] ch_rd_clr_stall;
  reg [2:0] load_wr_num;
  reg load_wr;
  wire [7:0] ch_load_wr;
  reg [2:0] ch_fifo_wr_num;
  reg [2:0] rd_transfer_num;
  reg [2:0] rd_clr_line_num;
  reg rd_transfer;
  reg rd_clr_line;
  reg fifo_wr;
  wire [7:0] ch_rd_transfer;
  wire [7:0] ch_rd_clr_line;
  wire [7:0] ch_fifo_wr;
  reg [2:0] rd_ch_num_resp;
  reg rd_slverr;
  reg rd_decerr;
  reg rd_clr;
  reg rd_clr_load;
  wire [7:0] ch_rd_slverr;
  wire [7:0] ch_rd_decerr;
  wire [7:0] ch_rd_clr;
  wire [7:0] ch_rd_clr_load;
  reg [2:0] wr_ch_num;
  reg [2:0] wr_cmd_num;
  wire wr_last_cmd;
  wire wr_line_cmd;
  wire wr_go_next_line;
  reg wr_burst_start;
  wire [31:0] wr_burst_addr;
  wire [7:0] wr_burst_size;
  wire wr_tokens;
  wire wr_cmd_port;
  wire wr_periph_delay;
  wire wr_clr_valid;
  reg wr_cmd_split;
  wire wr_clr_stall;
  reg [7:0] ch_wr_last_cmd;
  reg [7:0] ch_wr_line_cmd;
  reg [7:0] ch_wr_go_next_line;
  wire [7:0] ch_wr_burst_start;
  reg [255:0] ch_wr_burst_addr;
  reg [63:0] ch_wr_burst_size;
  reg ch_wr_tokens;
  reg [7:0] ch_wr_port_num;
  reg ch_wr_periph_delay;
  reg [7:0] ch_wr_clr_valid;
  wire [7:0] ch_wr_cmd_split;
  reg [7:0] ch_wr_clr_stall;
  reg [2:0] ch_fifo_rd_num;
  reg [2:0] wr_transfer_num;
  reg [2:0] wr_clr_line_num;
  reg wr_transfer;
  reg wr_clr_line;
  reg fifo_rd;
  reg [7:0] ch_fifo_wr_ready;
  wire [7:0] ch_wr_transfer;
  wire [7:0] ch_wr_clr_line;
  wire [7:0] ch_fifo_rd;
  wire fifo_wr_ready;
  reg [2:0] wr_ch_num_resp;
  reg wr_slverr;
  reg wr_decerr;
  reg wr_clr;
  reg wr_clr_last;
  wire [7:0] ch_wr_slverr;
  wire [7:0] ch_wr_decerr;
  wire [7:0] ch_wr_clr_last;
  wire [7:0] ch_wr_clr;

  // DUT instantiation
  dma_axi64_core0_channels_mux dut (
    .ch_fifo_rd_valid(ch_fifo_rd_valid),
    .fifo_rd_valid(fifo_rd_valid),
    .ch_fifo_rdata(ch_fifo_rdata),
    .fifo_rdata(fifo_rdata),
    .ch_periph_rx_clr(ch_periph_rx_clr),
    .periph_rx_clr(periph_rx_clr),
    .ch_periph_tx_clr(ch_periph_tx_clr),
    .periph_tx_clr(periph_tx_clr),
    .ch_rd_page_cross(ch_rd_page_cross),
    .ch_wr_page_cross(ch_wr_page_cross),
    .rd_page_cross(rd_page_cross),
    .wr_page_cross(wr_page_cross),
    .timeout_aw(timeout_aw),
    .timeout_w(timeout_w),
    .timeout_ar(timeout_ar),
    .timeout_num_aw(timeout_num_aw),
    .timeout_num_w(timeout_num_w),
    .timeout_num_ar(timeout_num_ar),
    .wdt_timeout(wdt_timeout),
    .wdt_ch_num(wdt_ch_num),
    .ch_timeout_aw(ch_timeout_aw),
    .ch_timeout_w(ch_timeout_w),
    .ch_timeout_ar(ch_timeout_ar),
    .ch_wdt_timeout(ch_wdt_timeout),
    .joint_in_prog(joint_in_prog),
    .joint_not_in_prog(joint_not_in_prog),
    .joint_mux_in_prog(joint_mux_in_prog),
    .ch_joint_in_prog(ch_joint_in_prog),
    .ch_joint_not_in_prog(ch_joint_not_in_prog),
    .ch_joint_mux_in_prog(ch_joint_mux_in_prog),
    .wr_cmd_pending(wr_cmd_pending),
    .ch_wr_cmd_pending(ch_wr_cmd_pending),
    .rd_ch_num(rd_ch_num),
    .rd_cmd_num(rd_cmd_num),
    .load_req_in_prog(load_req_in_prog),
    .rd_line_cmd(rd_line_cmd),
    .rd_go_next_line(rd_go_next_line),
    .rd_burst_start(rd_burst_start),
    .rd_burst_addr(rd_burst_addr),
    .rd_burst_size(rd_burst_size),
    .rd_tokens(rd_tokens),
    .rd_cmd_port(rd_cmd_port),
    .rd_periph_delay(rd_periph_delay),
    .rd_clr_valid(rd_clr_valid),
    .rd_cmd_split(rd_cmd_split),
    .rd_cmd_line(rd_cmd_line),
    .rd_clr_stall(rd_clr_stall),
    .ch_load_req_in_prog(ch_load_req_in_prog),
    .ch_rd_line_cmd(ch_rd_line_cmd),
    .ch_rd_go_next_line(ch_rd_go_next_line),
    .ch_rd_burst_start(ch_rd_burst_start),
    .ch_rd_burst_addr(ch_rd_burst_addr),
    .ch_rd_burst_size(ch_rd_burst_size),
    .ch_rd_tokens(ch_rd_tokens),
    .ch_rd_port_num(ch_rd_port_num),
    .ch_rd_periph_delay(ch_rd_periph_delay),
    .ch_rd_clr_valid(ch_rd_clr_valid),
    .ch_rd_cmd_split(ch_rd_cmd_split),
    .ch_rd_cmd_line(ch_rd_cmd_line),
    .ch_rd_clr_stall(ch_rd_clr_stall),
    .load_wr_num(load_wr_num),
    .load_wr(load_wr),
    .ch_load_wr(ch_load_wr),
    .ch_fifo_wr_num(ch_fifo_wr_num),
    .rd_transfer_num(rd_transfer_num),
    .rd_clr_line_num(rd_clr_line_num),
    .rd_transfer(rd_transfer),
    .rd_clr_line(rd_clr_line),
    .fifo_wr(fifo_wr),
    .ch_rd_transfer(ch_rd_transfer),
    .ch_rd_clr_line(ch_rd_clr_line),
    .ch_fifo_wr(ch_fifo_wr),
    .rd_ch_num_resp(rd_ch_num_resp),
    .rd_slverr(rd_slverr),
    .rd_decerr(rd_decerr),
    .rd_clr(rd_clr),
    .rd_clr_load(rd_clr_load),
    .ch_rd_slverr(ch_rd_slverr),
    .ch_rd_decerr(ch_rd_decerr),
    .ch_rd_clr(ch_rd_clr),
    .ch_rd_clr_load(ch_rd_clr_load),
    .wr_ch_num(wr_ch_num),
    .wr_cmd_num(wr_cmd_num),
    .wr_last_cmd(wr_last_cmd),
    .wr_line_cmd(wr_line_cmd),
    .wr_go_next_line(wr_go_next_line),
    .wr_burst_start(wr_burst_start),
    .wr_burst_addr(wr_burst_addr),
    .wr_burst_size(wr_burst_size),
    .wr_tokens(wr_tokens),
    .wr_cmd_port(wr_cmd_port),
    .wr_periph_delay(wr_periph_delay),
    .wr_clr_valid(wr_clr_valid),
    .wr_cmd_split(wr_cmd_split),
    .wr_clr_stall(wr_clr_stall),
    .ch_wr_last_cmd(ch_wr_last_cmd),
    .ch_wr_line_cmd(ch_wr_line_cmd),
    .ch_wr_go_next_line(ch_wr_go_next_line),
    .ch_wr_burst_start(ch_wr_burst_start),
    .ch_wr_burst_addr(ch_wr_burst_addr),
    .ch_wr_burst_size(ch_wr_burst_size),
    .ch_wr_tokens(ch_wr_tokens),
    .ch_wr_port_num(ch_wr_port_num),
    .ch_wr_periph_delay(ch_wr_periph_delay),
    .ch_wr_clr_valid(ch_wr_clr_valid),
    .ch_wr_cmd_split(ch_wr_cmd_split),
    .ch_wr_clr_stall(ch_wr_clr_stall),
    .ch_fifo_rd_num(ch_fifo_rd_num),
    .wr_transfer_num(wr_transfer_num),
    .wr_clr_line_num(wr_clr_line_num),
    .wr_transfer(wr_transfer),
    .wr_clr_line(wr_clr_line),
    .fifo_rd(fifo_rd),
    .ch_fifo_wr_ready(ch_fifo_wr_ready),
    .ch_wr_transfer(ch_wr_transfer),
    .ch_wr_clr_line(ch_wr_clr_line),
    .ch_fifo_rd(ch_fifo_rd),
    .fifo_wr_ready(fifo_wr_ready),
    .wr_ch_num_resp(wr_ch_num_resp),
    .wr_slverr(wr_slverr),
    .wr_decerr(wr_decerr),
    .wr_clr(wr_clr),
    .wr_clr_last(wr_clr_last),
    .ch_wr_slverr(ch_wr_slverr),
    .ch_wr_decerr(ch_wr_decerr),
    .ch_wr_clr_last(ch_wr_clr_last),
    .ch_wr_clr(ch_wr_clr)
  );

  initial begin
    ch_fifo_rd_valid = '0;
    ch_fifo_rdata = '0;
    ch_periph_rx_clr = '0;
    ch_periph_tx_clr = '0;
    rd_page_cross = '0;
    wr_page_cross = '0;
    timeout_aw = '0;
    timeout_w = '0;
    timeout_ar = '0;
    timeout_num_aw = '0;
    timeout_num_w = '0;
    timeout_num_ar = '0;
    wdt_timeout = '0;
    wdt_ch_num = '0;
    ch_joint_in_prog = '0;
    ch_joint_not_in_prog = '0;
    ch_joint_mux_in_prog = '0;
    wr_cmd_pending = '0;
    rd_ch_num = '0;
    rd_cmd_num = '0;
    rd_cmd_split = '0;
    rd_cmd_line = '0;
    ch_load_req_in_prog = '0;
    ch_rd_line_cmd = '0;
    ch_rd_go_next_line = '0;
    ch_rd_tokens = '0;
    ch_rd_port_num = '0;
    ch_rd_periph_delay = '0;
    ch_rd_clr_valid = '0;
    ch_rd_clr_stall = '0;
    load_wr_num = '0;
    load_wr = '0;
    ch_fifo_wr_num = '0;
    rd_transfer_num = '0;
    rd_clr_line_num = '0;
    rd_transfer = '0;
    rd_clr_line = '0;
    fifo_wr = '0;
    rd_ch_num_resp = '0;
    rd_slverr = '0;
    rd_decerr = '0;
    rd_clr = '0;
    rd_clr_load = '0;
    wr_ch_num = '0;
    wr_cmd_num = '0;
    wr_cmd_split = '0;
    ch_wr_last_cmd = '0;
    ch_wr_line_cmd = '0;
    ch_wr_go_next_line = '0;
    ch_wr_tokens = '0;
    ch_wr_port_num = '0;
    ch_wr_periph_delay = '0;
    ch_wr_clr_valid = '0;
    ch_wr_clr_stall = '0;
    ch_fifo_rd_num = '0;
    wr_transfer_num = '0;
    wr_clr_line_num = '0;
    wr_transfer = '0;
    wr_clr_line = '0;
    fifo_rd = '0;
    ch_fifo_wr_ready = '0;
    wr_ch_num_resp = '0;
    wr_slverr = '0;
    wr_decerr = '0;
    wr_clr = '0;
    wr_clr_last = '0;
    rd_burst_start = 1'b1;  // active-high reset asserted
    ch_rd_burst_addr = 1'b1;  // active-high reset asserted
    ch_rd_burst_size = 1'b1;  // active-high reset asserted
    wr_burst_start = 1'b1;  // active-high reset asserted
    ch_wr_burst_addr = 1'b1;  // active-high reset asserted
    ch_wr_burst_size = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    rd_burst_start = 1'b0;  // release active-high reset
    ch_rd_burst_addr = 1'b0;  // release active-high reset
    ch_rd_burst_size = 1'b0;  // release active-high reset
    wr_burst_start = 1'b0;  // release active-high reset
    ch_wr_burst_addr = 1'b0;  // release active-high reset
    ch_wr_burst_size = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_channels_mux compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_channels_mux");
    $finish;
  end

endmodule
