// Auto-generated testbench for dma_axi64_reg
// Source: dma_axi64_reg.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_reg;

  reg clk;
  reg reset;
  reg pclken;
  reg psel;
  reg penable;
  reg [7:0] paddr;
  reg pwrite;
  reg [31:0] pwdata;
  wire [31:0] prdata;
  wire pslverr;
  reg core0_idle;
  reg [7:0] ch_int_all_proc0;
  wire int_all_proc;
  wire [3:0] core0_clkdiv;
  wire [7:0] core0_ch_start;
  wire joint_mode0;
  wire rd_prio_top0;
  wire rd_prio_high0;
  wire [2:0] rd_prio_top_num0;
  wire [2:0] rd_prio_high_num0;
  wire wr_prio_top0;
  wire wr_prio_high0;
  wire [2:0] wr_prio_top_num0;
  wire [2:0] wr_prio_high_num0;
  wire [30:0] periph_rx_req_reg;
  wire [30:0] periph_tx_req_reg;
  reg [30:0] periph_rx_clr;
  reg [30:0] periph_tx_clr;

  // DUT instantiation
  dma_axi64_reg #(
    // .PROC0_STATUS(),
    // .PROC1_STATUS(),
    // .PROC2_STATUS(),
    // .PROC3_STATUS(),
    // .PROC4_STATUS(),
    // .PROC5_STATUS(),
    // .PROC6_STATUS(),
    // .PROC7_STATUS(),
    // .CORE0_JOINT(),
    // .CORE1_JOINT(),
    // .CORE0_PRIO(),
    // .CORE1_PRIO(),
    // .CORE0_CLKDIV(),
    // .CORE1_CLKDIV(),
    // .CORE0_START(),
    // .CORE1_START(),
    // .PERIPH_RX_CTRL(),
    // .PERIPH_TX_CTRL(),
    // .IDLE(),
    // .USER_DEF_STAT(),
    // .USER_DEF0_STAT0(),
    // .USER_DEF0_STAT1(),
    // .USER_DEF1_STAT0(),
    // .USER_DEF1_STAT1()
  ) dut (
    .clk(clk),
    .reset(reset),
    .pclken(pclken),
    .psel(psel),
    .penable(penable),
    .paddr(paddr),
    .pwrite(pwrite),
    .pwdata(pwdata),
    .prdata(prdata),
    .pslverr(pslverr),
    .core0_idle(core0_idle),
    .ch_int_all_proc0(ch_int_all_proc0),
    .int_all_proc(int_all_proc),
    .core0_clkdiv(core0_clkdiv),
    .core0_ch_start(core0_ch_start),
    .joint_mode0(joint_mode0),
    .rd_prio_top0(rd_prio_top0),
    .rd_prio_high0(rd_prio_high0),
    .rd_prio_top_num0(rd_prio_top_num0),
    .rd_prio_high_num0(rd_prio_high_num0),
    .wr_prio_top0(wr_prio_top0),
    .wr_prio_high0(wr_prio_high0),
    .wr_prio_top_num0(wr_prio_top_num0),
    .wr_prio_high_num0(wr_prio_high_num0),
    .periph_rx_req_reg(periph_rx_req_reg),
    .periph_tx_req_reg(periph_tx_req_reg),
    .periph_rx_clr(periph_rx_clr),
    .periph_tx_clr(periph_tx_clr)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  // Clock generation: pclken
  initial pclken = 1'b0;
  always #5 pclken = ~pclken;

  initial begin
    psel = '0;
    penable = '0;
    paddr = '0;
    pwrite = '0;
    pwdata = '0;
    core0_idle = '0;
    ch_int_all_proc0 = '0;
    periph_rx_clr = '0;
    periph_tx_clr = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_reg compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_reg");
    $finish;
  end

endmodule
