// Auto-generated testbench for dma_axi32_core0_axim_wdata
// Source: dma_axi32_core0_axim_wdata.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_axim_wdata;

  reg clk;
  reg reset;
  reg rd_transfer;
  reg [2:0] rd_transfer_size;
  wire ch_fifo_rd;
  wire [2:0] ch_fifo_rsize;
  reg [31:0] ch_fifo_rdata;
  reg ch_fifo_rd_valid;
  reg ch_fifo_wr_ready;
  wire [2:0] ch_fifo_rd_num;
  wire [2:0] wr_transfer_num;
  wire wr_transfer;
  wire [2:0] wr_transfer_size;
  wire [2:0] wr_next_size;
  reg wr_resp_full;
  wire wr_cmd_full;
  wire wr_clr_line;
  wire [2:0] wr_clr_line_num;
  wire joint_stall;
  wire [2:0] axim_timeout_num;
  wire axim_timeout;
  reg AWID;
  reg [31:0] AWADDR;
  reg AWLEN;
  reg [1:0] AWSIZE;
  reg AWVALID;
  reg AWREADY;
  reg AJOINT;
  wire [31:0] WDATA;
  wire [3:0] WSTRB;
  wire WLAST;
  wire WVALID;
  reg WREADY;

  // DUT instantiation
  dma_axi32_core0_axim_wdata dut (
    .clk(clk),
    .reset(reset),
    .rd_transfer(rd_transfer),
    .rd_transfer_size(rd_transfer_size),
    .ch_fifo_rd(ch_fifo_rd),
    .ch_fifo_rsize(ch_fifo_rsize),
    .ch_fifo_rdata(ch_fifo_rdata),
    .ch_fifo_rd_valid(ch_fifo_rd_valid),
    .ch_fifo_wr_ready(ch_fifo_wr_ready),
    .ch_fifo_rd_num(ch_fifo_rd_num),
    .wr_transfer_num(wr_transfer_num),
    .wr_transfer(wr_transfer),
    .wr_transfer_size(wr_transfer_size),
    .wr_next_size(wr_next_size),
    .wr_resp_full(wr_resp_full),
    .wr_cmd_full(wr_cmd_full),
    .wr_clr_line(wr_clr_line),
    .wr_clr_line_num(wr_clr_line_num),
    .joint_stall(joint_stall),
    .axim_timeout_num(axim_timeout_num),
    .axim_timeout(axim_timeout),
    .AWID(AWID),
    .AWADDR(AWADDR),
    .AWLEN(AWLEN),
    .AWSIZE(AWSIZE),
    .AWVALID(AWVALID),
    .AWREADY(AWREADY),
    .AJOINT(AJOINT),
    .WDATA(WDATA),
    .WSTRB(WSTRB),
    .WLAST(WLAST),
    .WVALID(WVALID),
    .WREADY(WREADY)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    rd_transfer = '0;
    rd_transfer_size = '0;
    ch_fifo_rdata = '0;
    ch_fifo_rd_valid = '0;
    ch_fifo_wr_ready = '0;
    wr_resp_full = '0;
    AWID = '0;
    AWADDR = '0;
    AWLEN = '0;
    AWSIZE = '0;
    AWVALID = '0;
    AWREADY = '0;
    AJOINT = '0;
    WREADY = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_axim_wdata compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_axim_wdata");
    $finish;
  end

endmodule
