// Auto-generated testbench for dma_axi64_core0_ch_offsets
// Source: dma_axi64_core0_ch_offsets.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_ch_offsets;

  reg clk;
  reg reset;
  reg ch_update;
  reg burst_start;
  reg burst_last;
  reg [7:0] burst_size;
  reg load_req_in_prog;
  reg [9:0] x_size;
  reg [11:0] y_size;
  wire [9:0] x_offset;
  wire [11:0] y_offset;
  wire [9:0] x_remain;
  wire [11:0] clr_remain;
  wire ch_end;
  wire go_next_line;
  reg incr;
  reg clr_line;
  wire line_empty;
  wire empty;
  reg [2:0] start_align;
  reg [2:0] width_align;
  wire [2:0] align;

  // DUT instantiation
  dma_axi64_core0_ch_offsets dut (
    .clk(clk),
    .reset(reset),
    .ch_update(ch_update),
    .burst_start(burst_start),
    .burst_last(burst_last),
    .burst_size(burst_size),
    .load_req_in_prog(load_req_in_prog),
    .x_size(x_size),
    .y_size(y_size),
    .x_offset(x_offset),
    .y_offset(y_offset),
    .x_remain(x_remain),
    .clr_remain(clr_remain),
    .ch_end(ch_end),
    .go_next_line(go_next_line),
    .incr(incr),
    .clr_line(clr_line),
    .line_empty(line_empty),
    .empty(empty),
    .start_align(start_align),
    .width_align(width_align),
    .align(align)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    ch_update = '0;
    load_req_in_prog = '0;
    x_size = '0;
    y_size = '0;
    incr = '0;
    clr_line = '0;
    start_align = '0;
    width_align = '0;
    reset = 1'b1;  // active-high reset asserted
    burst_start = 1'b1;  // active-high reset asserted
    burst_last = 1'b1;  // active-high reset asserted
    burst_size = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    burst_start = 1'b0;  // release active-high reset
    burst_last = 1'b0;  // release active-high reset
    burst_size = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_ch_offsets compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_ch_offsets");
    $finish;
  end

endmodule
