// Auto-generated testbench for dma_axi32_core0_ch_reg_size
// Source: dma_axi32_core0_ch_reg_size.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_ch_reg_size;

  reg clk;
  reg reset;
  reg update;
  reg [31:0] start_addr;
  reg [6:0] burst_max_size_reg;
  reg [6:0] burst_max_size_other;
  reg allow_full_burst;
  reg allow_full_fifo;
  reg joint_flush;
  wire [6:0] burst_max_size;

  // DUT instantiation
  dma_axi32_core0_ch_reg_size #(
    // .MAX_BURST(),
    // .HALF_BYTES(),
    // .LARGE_FIFO(),
    // .SMALL_FIFO()
  ) dut (
    .clk(clk),
    .reset(reset),
    .update(update),
    .start_addr(start_addr),
    .burst_max_size_reg(burst_max_size_reg),
    .burst_max_size_other(burst_max_size_other),
    .allow_full_burst(allow_full_burst),
    .allow_full_fifo(allow_full_fifo),
    .joint_flush(joint_flush),
    .burst_max_size(burst_max_size)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    update = '0;
    start_addr = '0;
    allow_full_fifo = '0;
    joint_flush = '0;
    reset = 1'b1;  // active-high reset asserted
    burst_max_size_reg = 1'b1;  // active-high reset asserted
    burst_max_size_other = 1'b1;  // active-high reset asserted
    allow_full_burst = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    burst_max_size_reg = 1'b0;  // release active-high reset
    burst_max_size_other = 1'b0;  // release active-high reset
    allow_full_burst = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_ch_reg_size compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_ch_reg_size");
    $finish;
  end

endmodule
