// Auto-generated testbench for dma_axi32_core0_ch_rd_slicer
// Source: dma_axi32_core0_ch_rd_slicer.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_ch_rd_slicer;

  reg clk;
  reg reset;
  reg fifo_rd;
  reg [31:0] fifo_rdata;
  reg [2:0] fifo_rsize;
  reg [1:0] rd_align;
  reg [4:0] rd_ptr;
  reg [2:0] rd_line_remain;
  reg wr_incr;
  reg wr_single;
  wire slice_rd;
  wire [31:0] slice_rdata;
  wire [2:0] slice_rsize;
  wire [4:0] slice_rd_ptr;
  wire slice_rd_valid;

  // DUT instantiation
  dma_axi32_core0_ch_rd_slicer dut (
    .clk(clk),
    .reset(reset),
    .fifo_rd(fifo_rd),
    .fifo_rdata(fifo_rdata),
    .fifo_rsize(fifo_rsize),
    .rd_align(rd_align),
    .rd_ptr(rd_ptr),
    .rd_line_remain(rd_line_remain),
    .wr_incr(wr_incr),
    .wr_single(wr_single),
    .slice_rd(slice_rd),
    .slice_rdata(slice_rdata),
    .slice_rsize(slice_rsize),
    .slice_rd_ptr(slice_rd_ptr),
    .slice_rd_valid(slice_rd_valid)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    fifo_rd = '0;
    fifo_rdata = '0;
    fifo_rsize = '0;
    rd_align = '0;
    rd_ptr = '0;
    rd_line_remain = '0;
    wr_incr = '0;
    wr_single = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_ch_rd_slicer compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_ch_rd_slicer");
    $finish;
  end

endmodule
