// Auto-generated testbench for dma_axi64_core0_axim_rdata
// Source: dma_axi64_core0_axim_rdata.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_axim_rdata;

  reg clk;
  reg reset;
  reg joint_stall;
  wire ch_fifo_wr;
  wire [63:0] ch_fifo_wdata;
  wire [3:0] ch_fifo_wsize;
  wire [2:0] ch_fifo_wr_num;
  wire [2:0] rd_transfer_num;
  wire rd_transfer;
  reg [3:0] rd_transfer_size;
  wire rd_burst_cmd;
  wire load_wr;
  wire [2:0] load_wr_num;
  wire [1:0] load_wr_cycle;
  wire [63:0] load_wdata;
  wire rd_clr_line;
  wire [2:0] rd_clr_line_num;
  reg ARVALID;
  reg ARREADY;
  reg ARID;
  reg RID;
  reg [63:0] RDATA;
  reg RLAST;
  reg RVALID;
  reg RREADY;
  wire RREADY_out;

  // DUT instantiation
  dma_axi64_core0_axim_rdata dut (
    .clk(clk),
    .reset(reset),
    .joint_stall(joint_stall),
    .ch_fifo_wr(ch_fifo_wr),
    .ch_fifo_wdata(ch_fifo_wdata),
    .ch_fifo_wsize(ch_fifo_wsize),
    .ch_fifo_wr_num(ch_fifo_wr_num),
    .rd_transfer_num(rd_transfer_num),
    .rd_transfer(rd_transfer),
    .rd_transfer_size(rd_transfer_size),
    .rd_burst_cmd(rd_burst_cmd),
    .load_wr(load_wr),
    .load_wr_num(load_wr_num),
    .load_wr_cycle(load_wr_cycle),
    .load_wdata(load_wdata),
    .rd_clr_line(rd_clr_line),
    .rd_clr_line_num(rd_clr_line_num),
    .ARVALID(ARVALID),
    .ARREADY(ARREADY),
    .ARID(ARID),
    .RID(RID),
    .RDATA(RDATA),
    .RLAST(RLAST),
    .RVALID(RVALID),
    .RREADY(RREADY),
    .RREADY_out(RREADY_out)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    joint_stall = '0;
    rd_transfer_size = '0;
    ARVALID = '0;
    ARREADY = '0;
    ARID = '0;
    RID = '0;
    RDATA = '0;
    RLAST = '0;
    RVALID = '0;
    RREADY = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_axim_rdata compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_axim_rdata");
    $finish;
  end

endmodule
