// Auto-generated testbench for prgen_fifo
// Source: prgen_fifo.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_prgen_fifo;

  reg clk;
  reg reset;
  reg push;
  reg pop;
  reg [7:0] din;
  wire [7:0] dout;
  wire empty;
  wire full;

  // DUT instantiation
  prgen_fifo #(
    // .WIDTH(),
    // .DEPTH_FULL(),
    // .SINGLE(),
    // .DEPTH(),
    // .DEPTH_BITS(),
    // .LAST_LINE()
  ) dut (
    .clk(clk),
    .reset(reset),
    .push(push),
    .pop(pop),
    .din(din),
    .dout(dout),
    .empty(empty),
    .full(full)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    push = '0;
    pop = '0;
    din = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_prgen_fifo compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_prgen_fifo");
    $finish;
  end

endmodule
