// Auto-generated testbench for dma_axi64_core0_axim_rd
// Source: dma_axi64_core0_axim_rd.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_axim_rd;

  reg clk;
  reg reset;
  wire load_wr;
  wire [2:0] load_wr_num;
  wire [1:0] load_wr_cycle;
  wire [63:0] load_wdata;
  reg joint_stall;
  reg joint_req;
  reg rd_line_cmd;
  reg load_req_in_prog;
  reg rd_cmd_port;
  reg [2:0] rd_ch_num;
  reg rd_burst_start;
  reg [31:0] rd_burst_addr;
  reg [7:0] rd_burst_size;
  wire rd_cmd_pending;
  wire rd_cmd_split;
  wire rd_cmd_line;
  wire [2:0] rd_cmd_num;
  wire rd_cmd_full;
  wire ch_fifo_wr;
  wire [63:0] ch_fifo_wdata;
  wire [3:0] ch_fifo_wsize;
  wire [2:0] ch_fifo_wr_num;
  wire [2:0] rd_transfer_num;
  wire rd_transfer;
  wire [3:0] rd_transfer_size;
  wire rd_burst_cmd;
  wire rd_clr_line;
  wire [2:0] rd_clr_line_num;
  wire rd_slverr;
  wire rd_decerr;
  wire rd_clr;
  wire rd_clr_load;
  wire rd_clr_last;
  wire [2:0] rd_ch_num_resp;
  wire page_cross;
  wire [31:0] ARADDR;
  wire ARPORT;
  wire ARLEN;
  wire [1:0] ARSIZE;
  wire ARVALID;
  reg ARREADY;
  reg AWVALID;
  reg [63:0] RDATA;
  reg [1:0] RRESP;
  reg RLAST;
  reg RVALID;
  wire RREADY_out;
  wire axim_timeout_ar;
  wire [2:0] axim_timeout_num_ar;

  // DUT instantiation
  dma_axi64_core0_axim_rd dut (
    .clk(clk),
    .reset(reset),
    .load_wr(load_wr),
    .load_wr_num(load_wr_num),
    .load_wr_cycle(load_wr_cycle),
    .load_wdata(load_wdata),
    .joint_stall(joint_stall),
    .joint_req(joint_req),
    .rd_line_cmd(rd_line_cmd),
    .load_req_in_prog(load_req_in_prog),
    .rd_cmd_port(rd_cmd_port),
    .rd_ch_num(rd_ch_num),
    .rd_burst_start(rd_burst_start),
    .rd_burst_addr(rd_burst_addr),
    .rd_burst_size(rd_burst_size),
    .rd_cmd_pending(rd_cmd_pending),
    .rd_cmd_split(rd_cmd_split),
    .rd_cmd_line(rd_cmd_line),
    .rd_cmd_num(rd_cmd_num),
    .rd_cmd_full(rd_cmd_full),
    .ch_fifo_wr(ch_fifo_wr),
    .ch_fifo_wdata(ch_fifo_wdata),
    .ch_fifo_wsize(ch_fifo_wsize),
    .ch_fifo_wr_num(ch_fifo_wr_num),
    .rd_transfer_num(rd_transfer_num),
    .rd_transfer(rd_transfer),
    .rd_transfer_size(rd_transfer_size),
    .rd_burst_cmd(rd_burst_cmd),
    .rd_clr_line(rd_clr_line),
    .rd_clr_line_num(rd_clr_line_num),
    .rd_slverr(rd_slverr),
    .rd_decerr(rd_decerr),
    .rd_clr(rd_clr),
    .rd_clr_load(rd_clr_load),
    .rd_clr_last(rd_clr_last),
    .rd_ch_num_resp(rd_ch_num_resp),
    .page_cross(page_cross),
    .ARADDR(ARADDR),
    .ARPORT(ARPORT),
    .ARLEN(ARLEN),
    .ARSIZE(ARSIZE),
    .ARVALID(ARVALID),
    .ARREADY(ARREADY),
    .AWVALID(AWVALID),
    .RDATA(RDATA),
    .RRESP(RRESP),
    .RLAST(RLAST),
    .RVALID(RVALID),
    .RREADY_out(RREADY_out),
    .axim_timeout_ar(axim_timeout_ar),
    .axim_timeout_num_ar(axim_timeout_num_ar)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    joint_stall = '0;
    joint_req = '0;
    rd_line_cmd = '0;
    load_req_in_prog = '0;
    rd_cmd_port = '0;
    rd_ch_num = '0;
    ARREADY = '0;
    AWVALID = '0;
    RDATA = '0;
    RRESP = '0;
    RLAST = '0;
    RVALID = '0;
    reset = 1'b1;  // active-high reset asserted
    rd_burst_start = 1'b1;  // active-high reset asserted
    rd_burst_addr = 1'b1;  // active-high reset asserted
    rd_burst_size = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    rd_burst_start = 1'b0;  // release active-high reset
    rd_burst_addr = 1'b0;  // release active-high reset
    rd_burst_size = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_axim_rd compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_axim_rd");
    $finish;
  end

endmodule
