// Auto-generated testbench for dma_axi64_core0_ch_outs
// Source: dma_axi64_core0_ch_outs.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_ch_outs;

  reg clk;
  reg reset;
  reg cmd;
  reg clr;
  reg outs_max;
  wire outs;
  wire outs_empty;
  wire stall;
  wire timeout;

  // DUT instantiation
  dma_axi64_core0_ch_outs dut (
    .clk(clk),
    .reset(reset),
    .cmd(cmd),
    .clr(clr),
    .outs_max(outs_max),
    .outs(outs),
    .outs_empty(outs_empty),
    .stall(stall),
    .timeout(timeout)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    cmd = '0;
    clr = '0;
    outs_max = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_ch_outs compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_ch_outs");
    $finish;
  end

endmodule
