// Auto-generated testbench for dma_axi64_core0_ch_calc_addr
// Source: dma_axi64_core0_ch_calc_addr.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_ch_calc_addr;

  reg clk;
  reg reset;
  reg ch_update_d;
  reg load_in_prog;
  reg [31:0] load_addr;
  reg go_next_line;
  reg burst_start;
  reg incr;
  reg [31:0] start_addr;
  reg frame_width;
  reg x_size;
  reg [7:0] burst_size;
  wire [31:0] burst_addr;

  // DUT instantiation
  dma_axi64_core0_ch_calc_addr dut (
    .clk(clk),
    .reset(reset),
    .ch_update_d(ch_update_d),
    .load_in_prog(load_in_prog),
    .load_addr(load_addr),
    .go_next_line(go_next_line),
    .burst_start(burst_start),
    .incr(incr),
    .start_addr(start_addr),
    .frame_width(frame_width),
    .x_size(x_size),
    .burst_size(burst_size),
    .burst_addr(burst_addr)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    ch_update_d = '0;
    load_in_prog = '0;
    load_addr = '0;
    go_next_line = '0;
    incr = '0;
    start_addr = '0;
    frame_width = '0;
    x_size = '0;
    reset = 1'b1;  // active-high reset asserted
    burst_start = 1'b1;  // active-high reset asserted
    burst_size = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    burst_start = 1'b0;  // release active-high reset
    burst_size = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_ch_calc_addr compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_ch_calc_addr");
    $finish;
  end

endmodule
