#!/usr/bin/env bash
# Compile script for dma_axi64_core0_ch_fifo_ptr testbench
# Generated by blockify generate_tb.py
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SLANG="${SLANG:-$ROOT_DIR/tools/bin/slang}"

# Verify slang exists
if [ ! -x "$SLANG" ]; then
    echo "ERROR: slang not found at $SLANG"
    echo "Run src/scripts/setup_slang.sh first"
    exit 1
fi

echo "Compiling: dma_axi64_core0_ch_fifo_ptr testbench"
"$SLANG" \
  "$SCRIPT_DIR/../../../../import/dma_axi/src/dma_axi64/dma_axi64_core0_ch_fifo_ptr.v" \
  "$SCRIPT_DIR/tb_dma_axi64_core0_ch_fifo_ptr.v" \
  -I "$SCRIPT_DIR/../../../../import/dma_axi/src/dma_axi64" \
  -I "$SCRIPT_DIR/../../../../import/dma_axi/src/dma_axi64" \
  --allow-use-before-declare \
  --lint-only \
  --timescale "1ns/1ps"

echo "PASS: dma_axi64_core0_ch_fifo_ptr testbench compiled successfully"