// Auto-generated testbench for prgen_min2
// Source: prgen_min2.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_prgen_min2;

  reg [7:0] a;
  reg [7:0] b;
  wire [7:0] min;

  // DUT instantiation
  prgen_min2 #(
    // .WIDTH()
  ) dut (
    .a(a),
    .b(b),
    .min(min)
  );

  initial begin
    a = '0;
    b = '0;

    // Wait for reset
    #100;


    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_prgen_min2 compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_prgen_min2");
    $finish;
  end

endmodule
