// Auto-generated testbench for prgen_rawstat
// Source: prgen_rawstat.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_prgen_rawstat;

  reg clk;
  reg reset;
  reg clear;
  reg write;
  reg [31:0] pwdata;
  reg [31:0] int_bus;
  wire [31:0] rawstat;

  // DUT instantiation
  prgen_rawstat #(
    // .SIZE()
  ) dut (
    .clk(clk),
    .reset(reset),
    .clear(clear),
    .write(write),
    .pwdata(pwdata),
    .int_bus(int_bus),
    .rawstat(rawstat)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    clear = '0;
    write = '0;
    pwdata = '0;
    int_bus = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_prgen_rawstat compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_prgen_rawstat");
    $finish;
  end

endmodule
