// Auto-generated testbench for prgen_or8
// Source: prgen_or8.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_prgen_or8;

  reg [63:0] ch_x;
  wire [7:0] x;

  // DUT instantiation
  prgen_or8 #(
    // .WIDTH()
  ) dut (
    .ch_x(ch_x),
    .x(x)
  );

  initial begin
    ch_x = '0;

    // Wait for reset
    #100;


    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_prgen_or8 compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_prgen_or8");
    $finish;
  end

endmodule
