// Auto-generated testbench for dma_axi64_core0_ch_fifo
// Source: dma_axi64_core0_ch_fifo.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_ch_fifo;

  reg CLK;
  reg WR;
  reg RD;
  reg [1:0] WR_ADDR;
  reg [1:0] RD_ADDR;
  reg [63:0] DIN;
  reg [7:0] BSEL;
  wire [63:0] DOUT;

  // DUT instantiation
  dma_axi64_core0_ch_fifo dut (
    .CLK(CLK),
    .WR(WR),
    .RD(RD),
    .WR_ADDR(WR_ADDR),
    .RD_ADDR(RD_ADDR),
    .DIN(DIN),
    .BSEL(BSEL),
    .DOUT(DOUT)
  );

  // Clock generation: CLK
  initial CLK = 1'b0;
  always #5 CLK = ~CLK;

  initial begin
    WR = '0;
    RD = '0;
    WR_ADDR = '0;
    RD_ADDR = '0;
    DIN = '0;
    BSEL = '0;

    // Wait for reset
    #100;


    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_ch_fifo compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_ch_fifo");
    $finish;
  end

endmodule
