// Auto-generated testbench for prgen_scatter8_1
// Source: prgen_scatter8_1.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_prgen_scatter8_1;

  reg [7:0] ch_x;
  wire [7:0] x;

  // DUT instantiation
  prgen_scatter8_1 #(
    // .CH_NUM()
  ) dut (
    .ch_x(ch_x),
    .x(x)
  );

  initial begin
    ch_x = '0;

    // Wait for reset
    #100;


    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_prgen_scatter8_1 compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_prgen_scatter8_1");
    $finish;
  end

endmodule
