// Auto-generated testbench for dma_axi32_core0_axim_resp
// Source: dma_axi32_core0_axim_resp.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_axim_resp;

  reg clk;
  reg reset;
  wire slverr;
  wire decerr;
  wire clr;
  wire clr_last;
  wire [2:0] ch_num_resp;
  wire resp_full;
  reg AID;
  reg AVALID;
  reg AREADY;
  reg [1:0] RESP;
  wire ID;
  reg VALID;
  reg READY;
  reg LAST;

  // DUT instantiation
  dma_axi32_core0_axim_resp #(
    // .CMD_DEPTH(),
    // .RESP_SLVERR(),
    // .RESP_DECERR()
  ) dut (
    .clk(clk),
    .reset(reset),
    .slverr(slverr),
    .decerr(decerr),
    .clr(clr),
    .clr_last(clr_last),
    .ch_num_resp(ch_num_resp),
    .resp_full(resp_full),
    .AID(AID),
    .AVALID(AVALID),
    .AREADY(AREADY),
    .RESP(RESP),
    .ID(ID),
    .VALID(VALID),
    .READY(READY),
    .LAST(LAST)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    AID = '0;
    AVALID = '0;
    AREADY = '0;
    RESP = '0;
    VALID = '0;
    READY = '0;
    LAST = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_axim_resp compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_axim_resp");
    $finish;
  end

endmodule
