// Auto-generated testbench for prgen_swap32
// Source: prgen_swap_32.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_prgen_swap32;

  reg [1:0] end_swap;
  reg [31:0] data_in;
  wire [31:0] data_out;
  reg [3:0] bsel_in;
  wire [3:0] bsel_out;

  // DUT instantiation
  prgen_swap32 dut (
    .end_swap(end_swap),
    .data_in(data_in),
    .data_out(data_out),
    .bsel_in(bsel_in),
    .bsel_out(bsel_out)
  );

  initial begin
    end_swap = '0;
    data_in = '0;
    bsel_in = '0;

    // Wait for reset
    #100;


    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_prgen_swap32 compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_prgen_swap32");
    $finish;
  end

endmodule
