// Auto-generated testbench for dma_axi64_core0_ch_calc_joint
// Source: dma_axi64_core0_ch_calc_joint.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_ch_calc_joint;

  reg clk;
  reg reset;
  reg joint_update;
  reg ch_end;
  reg ch_end_flush;
  reg joint_line_req_clr;
  reg wr_cmd_pending;
  reg [7:0] burst_size_pre2;
  reg [7:0] burst_max_size;
  reg fifo_not_ready;
  reg outs_empty;
  reg [9:0] x_remain;
  reg fifo_wr_ready;
  reg [5:0] fifo_remain;
  reg joint;
  reg page_cross;
  reg joint_cross;
  reg joint_ready_in;
  wire joint_ready_out;
  wire joint_line_req;
  wire joint_burst_req;
  wire joint_wait;
  wire joint_flush;
  reg joint_flush_in;
  wire joint_buffer_small;

  // DUT instantiation
  dma_axi64_core0_ch_calc_joint #(
    // .READ(),
    // .WRITE(),
    // .IDLE(),
    // .REQ_LINE(),
    // .READY_OUT(),
    // .READY(),
    // .CROSS(),
    // .BURST_REQ(),
    // .RECHK(),
    // .FLUSH()
  ) dut (
    .clk(clk),
    .reset(reset),
    .joint_update(joint_update),
    .ch_end(ch_end),
    .ch_end_flush(ch_end_flush),
    .joint_line_req_clr(joint_line_req_clr),
    .wr_cmd_pending(wr_cmd_pending),
    .burst_size_pre2(burst_size_pre2),
    .burst_max_size(burst_max_size),
    .fifo_not_ready(fifo_not_ready),
    .outs_empty(outs_empty),
    .x_remain(x_remain),
    .fifo_wr_ready(fifo_wr_ready),
    .fifo_remain(fifo_remain),
    .joint(joint),
    .page_cross(page_cross),
    .joint_cross(joint_cross),
    .joint_ready_in(joint_ready_in),
    .joint_ready_out(joint_ready_out),
    .joint_line_req(joint_line_req),
    .joint_burst_req(joint_burst_req),
    .joint_wait(joint_wait),
    .joint_flush(joint_flush),
    .joint_flush_in(joint_flush_in),
    .joint_buffer_small(joint_buffer_small)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    joint_update = '0;
    ch_end = '0;
    ch_end_flush = '0;
    joint_line_req_clr = '0;
    wr_cmd_pending = '0;
    fifo_not_ready = '0;
    outs_empty = '0;
    x_remain = '0;
    fifo_wr_ready = '0;
    fifo_remain = '0;
    joint = '0;
    page_cross = '0;
    joint_cross = '0;
    joint_ready_in = '0;
    joint_flush_in = '0;
    reset = 1'b1;  // active-high reset asserted
    burst_size_pre2 = 1'b1;  // active-high reset asserted
    burst_max_size = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    burst_size_pre2 = 1'b0;  // release active-high reset
    burst_max_size = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_ch_calc_joint compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_ch_calc_joint");
    $finish;
  end

endmodule
