// Auto-generated testbench for dma_axi32_core0_ctrl
// Source: dma_axi32_core0_ctrl.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_ctrl;

  reg clk;
  reg reset;
  reg ch_go;
  reg cmd_full;
  reg cmd_pending;
  reg joint_req;
  reg [2:0] ch_num;
  reg [2:0] ch_num_resp;
  reg go_next_line;
  reg periph_clr_valid;
  reg periph_clr;
  reg periph_clr_last;
  reg periph_delay;
  reg clr_stall;
  reg tokens;
  reg ch_ready;
  reg ch_last;
  wire burst_start;
  wire finish;
  wire busy;
  reg hold;

  // DUT instantiation
  dma_axi32_core0_ctrl #(
    // .IDLE(),
    // .CMD(),
    // .WAIT_CLR(),
    // .WAIT_DELAY(),
    // .STALL()
  ) dut (
    .clk(clk),
    .reset(reset),
    .ch_go(ch_go),
    .cmd_full(cmd_full),
    .cmd_pending(cmd_pending),
    .joint_req(joint_req),
    .ch_num(ch_num),
    .ch_num_resp(ch_num_resp),
    .go_next_line(go_next_line),
    .periph_clr_valid(periph_clr_valid),
    .periph_clr(periph_clr),
    .periph_clr_last(periph_clr_last),
    .periph_delay(periph_delay),
    .clr_stall(clr_stall),
    .tokens(tokens),
    .ch_ready(ch_ready),
    .ch_last(ch_last),
    .burst_start(burst_start),
    .finish(finish),
    .busy(busy),
    .hold(hold)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    ch_go = '0;
    cmd_full = '0;
    cmd_pending = '0;
    joint_req = '0;
    ch_num = '0;
    ch_num_resp = '0;
    go_next_line = '0;
    periph_clr_valid = '0;
    periph_clr = '0;
    periph_clr_last = '0;
    periph_delay = '0;
    clr_stall = '0;
    tokens = '0;
    ch_ready = '0;
    ch_last = '0;
    hold = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_ctrl compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_ctrl");
    $finish;
  end

endmodule
