// Auto-generated testbench for dma_axi32_reg_core0
// Source: dma_axi32_reg_core0.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_reg_core0;

  reg clk;
  reg reset;
  reg wr_joint;
  reg wr_clkdiv;
  reg wr_start;
  reg wr_prio;
  reg [31:0] pwdata;
  wire [3:0] clkdiv;
  wire [7:0] ch_start;
  wire joint_mode;
  wire rd_prio_top;
  wire rd_prio_high;
  wire [2:0] rd_prio_top_num;
  wire [2:0] rd_prio_high_num;
  wire wr_prio_top;
  wire wr_prio_high;
  wire [2:0] wr_prio_top_num;
  wire [2:0] wr_prio_high_num;
  wire [31:0] user_def_stat0;
  wire [31:0] user_def_stat1;
  reg [7:0] ch_int_all_proc;
  wire [7:0] proc0_int_stat;

  // DUT instantiation
  dma_axi32_reg_core0 dut (
    .clk(clk),
    .reset(reset),
    .wr_joint(wr_joint),
    .wr_clkdiv(wr_clkdiv),
    .wr_start(wr_start),
    .wr_prio(wr_prio),
    .pwdata(pwdata),
    .clkdiv(clkdiv),
    .ch_start(ch_start),
    .joint_mode(joint_mode),
    .rd_prio_top(rd_prio_top),
    .rd_prio_high(rd_prio_high),
    .rd_prio_top_num(rd_prio_top_num),
    .rd_prio_high_num(rd_prio_high_num),
    .wr_prio_top(wr_prio_top),
    .wr_prio_high(wr_prio_high),
    .wr_prio_top_num(wr_prio_top_num),
    .wr_prio_high_num(wr_prio_high_num),
    .user_def_stat0(user_def_stat0),
    .user_def_stat1(user_def_stat1),
    .ch_int_all_proc(ch_int_all_proc),
    .proc0_int_stat(proc0_int_stat)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  // Clock generation: wr_clkdiv
  initial wr_clkdiv = 1'b0;
  always #5 wr_clkdiv = ~wr_clkdiv;

  initial begin
    wr_joint = '0;
    wr_start = '0;
    wr_prio = '0;
    pwdata = '0;
    ch_int_all_proc = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_reg_core0 compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_reg_core0");
    $finish;
  end

endmodule
