// Auto-generated testbench for prgen_min3
// Source: prgen_min3.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_prgen_min3;

  reg clk;
  reg reset;
  reg [7:0] a;
  reg [7:0] b;
  reg [7:0] c;
  wire [7:0] min;

  // DUT instantiation
  prgen_min3 #(
    // .WIDTH()
  ) dut (
    .clk(clk),
    .reset(reset),
    .a(a),
    .b(b),
    .c(c),
    .min(min)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    a = '0;
    b = '0;
    c = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_prgen_min3 compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_prgen_min3");
    $finish;
  end

endmodule
