// Auto-generated testbench for dma_axi64_core0_axim_cmd
// Source: dma_axi64_core0_axim_cmd.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi64_core0_axim_cmd;

  reg clk;
  reg reset;
  reg [2:0] ch_num;
  reg burst_start;
  reg [31:0] burst_addr;
  reg [7:0] burst_size;
  reg end_line_cmd;
  reg extra_bit;
  reg cmd_port;
  reg joint_req;
  wire joint_pending;
  wire cmd_pending;
  reg cmd_full;
  wire cmd_split;
  wire [2:0] cmd_num;
  wire cmd_line;
  wire page_cross;
  wire AID;
  wire [31:0] AADDR;
  wire APORT;
  wire ALEN;
  wire [1:0] ASIZE;
  wire AVALID;
  reg AREADY;
  reg AWVALID;
  wire AJOINT;
  wire [2:0] axim_timeout_num;
  wire axim_timeout;

  // DUT instantiation
  dma_axi64_core0_axim_cmd #(
    // .AXI_WORD_SIZE(),
    // .AXI_3()
  ) dut (
    .clk(clk),
    .reset(reset),
    .ch_num(ch_num),
    .burst_start(burst_start),
    .burst_addr(burst_addr),
    .burst_size(burst_size),
    .end_line_cmd(end_line_cmd),
    .extra_bit(extra_bit),
    .cmd_port(cmd_port),
    .joint_req(joint_req),
    .joint_pending(joint_pending),
    .cmd_pending(cmd_pending),
    .cmd_full(cmd_full),
    .cmd_split(cmd_split),
    .cmd_num(cmd_num),
    .cmd_line(cmd_line),
    .page_cross(page_cross),
    .AID(AID),
    .AADDR(AADDR),
    .APORT(APORT),
    .ALEN(ALEN),
    .ASIZE(ASIZE),
    .AVALID(AVALID),
    .AREADY(AREADY),
    .AWVALID(AWVALID),
    .AJOINT(AJOINT),
    .axim_timeout_num(axim_timeout_num),
    .axim_timeout(axim_timeout)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    ch_num = '0;
    end_line_cmd = '0;
    extra_bit = '0;
    cmd_port = '0;
    joint_req = '0;
    cmd_full = '0;
    AREADY = '0;
    AWVALID = '0;
    reset = 1'b1;  // active-high reset asserted
    burst_start = 1'b1;  // active-high reset asserted
    burst_addr = 1'b1;  // active-high reset asserted
    burst_size = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    burst_start = 1'b0;  // release active-high reset
    burst_addr = 1'b0;  // release active-high reset
    burst_size = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi64_core0_axim_cmd compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi64_core0_axim_cmd");
    $finish;
  end

endmodule
