// Auto-generated testbench for dma_axi32_core0_ch_calc
// Source: dma_axi32_core0_ch_calc.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_ch_calc;

  reg clk;
  reg reset;
  reg load_in_prog;
  reg load_req_in_prog;
  reg [31:0] load_addr;
  reg ch_update;
  reg ch_end;
  reg ch_end_flush;
  reg go_next_line;
  reg burst_start;
  reg incr;
  reg wr_cmd_pending;
  reg outs_empty;
  reg [6:0] burst_max_size;
  reg [31:0] start_addr;
  reg frame_width;
  reg x_size;
  reg [9:0] x_remain;
  reg fifo_wr_ready;
  reg [5:0] fifo_remain;
  wire burst_last;
  wire [31:0] burst_addr;
  wire [6:0] burst_size;
  wire burst_ready;
  wire single;
  wire joint_ready_out;
  reg joint_ready_in;
  reg joint_line_req_in;
  wire joint_line_req_out;
  reg joint_burst_req_in;
  wire joint_burst_req_out;
  reg joint_line_req_clr;
  reg joint;
  reg page_cross;
  reg joint_cross;
  wire joint_flush;
  reg joint_flush_in;

  // DUT instantiation
  dma_axi32_core0_ch_calc #(
    // .READ(),
    // .SINGLE_SIZE()
  ) dut (
    .clk(clk),
    .reset(reset),
    .load_in_prog(load_in_prog),
    .load_req_in_prog(load_req_in_prog),
    .load_addr(load_addr),
    .ch_update(ch_update),
    .ch_end(ch_end),
    .ch_end_flush(ch_end_flush),
    .go_next_line(go_next_line),
    .burst_start(burst_start),
    .incr(incr),
    .wr_cmd_pending(wr_cmd_pending),
    .outs_empty(outs_empty),
    .burst_max_size(burst_max_size),
    .start_addr(start_addr),
    .frame_width(frame_width),
    .x_size(x_size),
    .x_remain(x_remain),
    .fifo_wr_ready(fifo_wr_ready),
    .fifo_remain(fifo_remain),
    .burst_last(burst_last),
    .burst_addr(burst_addr),
    .burst_size(burst_size),
    .burst_ready(burst_ready),
    .single(single),
    .joint_ready_out(joint_ready_out),
    .joint_ready_in(joint_ready_in),
    .joint_line_req_in(joint_line_req_in),
    .joint_line_req_out(joint_line_req_out),
    .joint_burst_req_in(joint_burst_req_in),
    .joint_burst_req_out(joint_burst_req_out),
    .joint_line_req_clr(joint_line_req_clr),
    .joint(joint),
    .page_cross(page_cross),
    .joint_cross(joint_cross),
    .joint_flush(joint_flush),
    .joint_flush_in(joint_flush_in)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    load_in_prog = '0;
    load_req_in_prog = '0;
    load_addr = '0;
    ch_update = '0;
    ch_end = '0;
    ch_end_flush = '0;
    go_next_line = '0;
    incr = '0;
    wr_cmd_pending = '0;
    outs_empty = '0;
    start_addr = '0;
    frame_width = '0;
    x_size = '0;
    x_remain = '0;
    fifo_wr_ready = '0;
    fifo_remain = '0;
    joint_ready_in = '0;
    joint_line_req_in = '0;
    joint_line_req_clr = '0;
    joint = '0;
    page_cross = '0;
    joint_cross = '0;
    joint_flush_in = '0;
    reset = 1'b1;  // active-high reset asserted
    burst_start = 1'b1;  // active-high reset asserted
    burst_max_size = 1'b1;  // active-high reset asserted
    joint_burst_req_in = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset
    burst_start = 1'b0;  // release active-high reset
    burst_max_size = 1'b0;  // release active-high reset
    joint_burst_req_in = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_ch_calc compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_ch_calc");
    $finish;
  end

endmodule
