// Auto-generated testbench for dma_axi32_core0_axim_timeout
// Source: dma_axi32_core0_axim_timeout.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_axim_timeout;

  reg clk;
  reg reset;
  reg VALID;
  reg READY;
  reg ID;
  wire [2:0] axim_timeout_num;
  wire axim_timeout;

  // DUT instantiation
  dma_axi32_core0_axim_timeout dut (
    .clk(clk),
    .reset(reset),
    .VALID(VALID),
    .READY(READY),
    .ID(ID),
    .axim_timeout_num(axim_timeout_num),
    .axim_timeout(axim_timeout)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  initial begin
    VALID = '0;
    READY = '0;
    ID = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_axim_timeout compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_axim_timeout");
    $finish;
  end

endmodule
