// Auto-generated testbench for dma_axi32
// Source: dma_axi32.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32;

  reg clk;
  reg reset;
  reg scan_en;
  wire idle;
  wire INT;
  reg [30:0] periph_tx_req;
  wire [30:0] periph_tx_clr;
  reg [30:0] periph_rx_req;
  wire [30:0] periph_rx_clr;
  reg pclken;
  reg psel;
  reg penable;
  reg [12:0] paddr;
  reg pwrite;
  reg [31:0] pwdata;
  wire [31:0] prdata;
  wire pslverr;
  wire pready;
  wire AWID0;
  wire [31:0] AWADDR0;
  wire [3:0] AWLEN0;
  wire [1:0] AWSIZE0;
  wire AWVALID0;
  reg AWREADY0;
  wire WID0;
  wire [31:0] WDATA0;
  wire [3:0] WSTRB0;
  wire WLAST0;
  wire WVALID0;
  reg WREADY0;
  reg BID0;
  reg [1:0] BRESP0;
  reg BVALID0;
  wire BREADY0;
  wire ARID0;
  wire [31:0] ARADDR0;
  wire [3:0] ARLEN0;
  wire [1:0] ARSIZE0;
  wire ARVALID0;
  reg ARREADY0;
  reg RID0;
  reg [31:0] RDATA0;
  reg [1:0] RRESP0;
  reg RLAST0;
  reg RVALID0;
  wire RREADY0;

  // DUT instantiation
  dma_axi32 dut (
    .clk(clk),
    .reset(reset),
    .scan_en(scan_en),
    .idle(idle),
    .INT(INT),
    .periph_tx_req(periph_tx_req),
    .periph_tx_clr(periph_tx_clr),
    .periph_rx_req(periph_rx_req),
    .periph_rx_clr(periph_rx_clr),
    .pclken(pclken),
    .psel(psel),
    .penable(penable),
    .paddr(paddr),
    .pwrite(pwrite),
    .pwdata(pwdata),
    .prdata(prdata),
    .pslverr(pslverr),
    .pready(pready),
    .AWID0(AWID0),
    .AWADDR0(AWADDR0),
    .AWLEN0(AWLEN0),
    .AWSIZE0(AWSIZE0),
    .AWVALID0(AWVALID0),
    .AWREADY0(AWREADY0),
    .WID0(WID0),
    .WDATA0(WDATA0),
    .WSTRB0(WSTRB0),
    .WLAST0(WLAST0),
    .WVALID0(WVALID0),
    .WREADY0(WREADY0),
    .BID0(BID0),
    .BRESP0(BRESP0),
    .BVALID0(BVALID0),
    .BREADY0(BREADY0),
    .ARID0(ARID0),
    .ARADDR0(ARADDR0),
    .ARLEN0(ARLEN0),
    .ARSIZE0(ARSIZE0),
    .ARVALID0(ARVALID0),
    .ARREADY0(ARREADY0),
    .RID0(RID0),
    .RDATA0(RDATA0),
    .RRESP0(RRESP0),
    .RLAST0(RLAST0),
    .RVALID0(RVALID0),
    .RREADY0(RREADY0)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  // Clock generation: pclken
  initial pclken = 1'b0;
  always #5 pclken = ~pclken;

  initial begin
    scan_en = '0;
    periph_tx_req = '0;
    periph_rx_req = '0;
    psel = '0;
    penable = '0;
    paddr = '0;
    pwrite = '0;
    pwdata = '0;
    AWREADY0 = '0;
    WREADY0 = '0;
    BID0 = '0;
    BRESP0 = '0;
    BVALID0 = '0;
    ARREADY0 = '0;
    RID0 = '0;
    RDATA0 = '0;
    RRESP0 = '0;
    RLAST0 = '0;
    RVALID0 = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32 compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32");
    $finish;
  end

endmodule
