// Auto-generated testbench for dma_axi32_core0_ch_reg
// Source: dma_axi32_core0_ch_reg.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_dma_axi32_core0_ch_reg;

  reg clk;
  reg clken;
  reg pclken;
  reg reset;
  reg psel;
  reg penable;
  reg [7:0] paddr;
  reg pwrite;
  reg [31:0] pwdata;
  wire [31:0] prdata;
  wire pslverr;
  reg [4:0] timeout_bus;
  reg wdt_timeout;
  reg ch_start;
  wire [31:0] load_addr;
  wire load_in_prog;
  wire load_req_in_prog;
  reg load_wr;
  reg [1:0] load_wr_cycle;
  reg [31:0] load_wdata;
  reg load_cmd;
  reg rd_ch_end;
  reg wr_ch_end;
  reg wr_clr_last;
  reg rd_slverr;
  reg rd_decerr;
  reg wr_slverr;
  reg wr_decerr;
  wire int_all_proc;
  wire ch_rd_active;
  wire ch_wr_active;
  wire ch_in_prog;
  reg [9:0] rd_x_offset;
  reg [11:0] rd_y_offset;
  reg [9:0] wr_x_offset;
  reg [11:0] wr_y_offset;
  reg [5:0] wr_fullness;
  reg [5:0] rd_gap;
  reg fifo_overflow;
  reg fifo_underflow;
  wire ch_update;
  wire [31:0] rd_start_addr;
  wire [31:0] wr_start_addr;
  wire [9:0] x_size;
  wire [11:0] y_size;
  wire [6:0] rd_burst_max_size;
  wire [6:0] wr_burst_max_size;
  wire block;
  reg allow_line_cmd;
  wire frame_width;
  wire [1:0] width_align;
  wire rd_periph_delay;
  wire rd_periph_block;
  wire wr_periph_delay;
  wire wr_periph_block;
  wire rd_tokens;
  wire wr_tokens;
  wire rd_port_num;
  wire wr_port_num;
  wire rd_outs_max;
  wire wr_outs_max;
  reg rd_outs;
  reg wr_outs;
  reg outs_empty;
  wire rd_wait_limit;
  wire wr_wait_limit;
  wire rd_incr;
  wire wr_incr;
  wire [4:0] rd_periph_num;
  wire [4:0] wr_periph_num;
  wire wr_outstanding;
  wire rd_outstanding;
  wire ch_retry_wait;
  reg joint_mode;
  reg joint_remote;
  reg joint_cross;
  reg page_cross;
  wire joint;
  reg joint_flush;
  wire [1:0] end_swap;

  // DUT instantiation
  dma_axi32_core0_ch_reg #(
    // .DATA_SHIFT(),
    // .CMD_LINE0(),
    // .CMD_LINE1(),
    // .CMD_LINE2(),
    // .CMD_LINE3(),
    // .STATIC_LINE0(),
    // .STATIC_LINE1(),
    // .STATIC_LINE2(),
    // .STATIC_LINE3(),
    // .STATIC_LINE4(),
    // .RESTRICT(),
    // .RD_OFFSETS(),
    // .WR_OFFSETS(),
    // .FIFO_FULLNESS(),
    // .CMD_OUTS(),
    // .CH_ENABLE(),
    // .CH_START(),
    // .CH_ACTIVE(),
    // .CH_CMD_COUNTER(),
    // .INT_RAWSTAT(),
    // .INT_CLEAR(),
    // .INT_ENABLE(),
    // .INT_STATUS(),
    // .INT_NUM()
  ) dut (
    .clk(clk),
    .clken(clken),
    .pclken(pclken),
    .reset(reset),
    .psel(psel),
    .penable(penable),
    .paddr(paddr),
    .pwrite(pwrite),
    .pwdata(pwdata),
    .prdata(prdata),
    .pslverr(pslverr),
    .timeout_bus(timeout_bus),
    .wdt_timeout(wdt_timeout),
    .ch_start(ch_start),
    .load_addr(load_addr),
    .load_in_prog(load_in_prog),
    .load_req_in_prog(load_req_in_prog),
    .load_wr(load_wr),
    .load_wr_cycle(load_wr_cycle),
    .load_wdata(load_wdata),
    .load_cmd(load_cmd),
    .rd_ch_end(rd_ch_end),
    .wr_ch_end(wr_ch_end),
    .wr_clr_last(wr_clr_last),
    .rd_slverr(rd_slverr),
    .rd_decerr(rd_decerr),
    .wr_slverr(wr_slverr),
    .wr_decerr(wr_decerr),
    .int_all_proc(int_all_proc),
    .ch_rd_active(ch_rd_active),
    .ch_wr_active(ch_wr_active),
    .ch_in_prog(ch_in_prog),
    .rd_x_offset(rd_x_offset),
    .rd_y_offset(rd_y_offset),
    .wr_x_offset(wr_x_offset),
    .wr_y_offset(wr_y_offset),
    .wr_fullness(wr_fullness),
    .rd_gap(rd_gap),
    .fifo_overflow(fifo_overflow),
    .fifo_underflow(fifo_underflow),
    .ch_update(ch_update),
    .rd_start_addr(rd_start_addr),
    .wr_start_addr(wr_start_addr),
    .x_size(x_size),
    .y_size(y_size),
    .rd_burst_max_size(rd_burst_max_size),
    .wr_burst_max_size(wr_burst_max_size),
    .block(block),
    .allow_line_cmd(allow_line_cmd),
    .frame_width(frame_width),
    .width_align(width_align),
    .rd_periph_delay(rd_periph_delay),
    .rd_periph_block(rd_periph_block),
    .wr_periph_delay(wr_periph_delay),
    .wr_periph_block(wr_periph_block),
    .rd_tokens(rd_tokens),
    .wr_tokens(wr_tokens),
    .rd_port_num(rd_port_num),
    .wr_port_num(wr_port_num),
    .rd_outs_max(rd_outs_max),
    .wr_outs_max(wr_outs_max),
    .rd_outs(rd_outs),
    .wr_outs(wr_outs),
    .outs_empty(outs_empty),
    .rd_wait_limit(rd_wait_limit),
    .wr_wait_limit(wr_wait_limit),
    .rd_incr(rd_incr),
    .wr_incr(wr_incr),
    .rd_periph_num(rd_periph_num),
    .wr_periph_num(wr_periph_num),
    .wr_outstanding(wr_outstanding),
    .rd_outstanding(rd_outstanding),
    .ch_retry_wait(ch_retry_wait),
    .joint_mode(joint_mode),
    .joint_remote(joint_remote),
    .joint_cross(joint_cross),
    .page_cross(page_cross),
    .joint(joint),
    .joint_flush(joint_flush),
    .end_swap(end_swap)
  );

  // Clock generation: clk
  initial clk = 1'b0;
  always #5 clk = ~clk;

  // Clock generation: clken
  initial clken = 1'b0;
  always #5 clken = ~clken;

  // Clock generation: pclken
  initial pclken = 1'b0;
  always #5 pclken = ~pclken;

  initial begin
    psel = '0;
    penable = '0;
    paddr = '0;
    pwrite = '0;
    pwdata = '0;
    timeout_bus = '0;
    wdt_timeout = '0;
    ch_start = '0;
    load_wr = '0;
    load_wr_cycle = '0;
    load_wdata = '0;
    load_cmd = '0;
    rd_ch_end = '0;
    wr_ch_end = '0;
    wr_clr_last = '0;
    rd_slverr = '0;
    rd_decerr = '0;
    wr_slverr = '0;
    wr_decerr = '0;
    rd_x_offset = '0;
    rd_y_offset = '0;
    wr_x_offset = '0;
    wr_y_offset = '0;
    wr_fullness = '0;
    rd_gap = '0;
    fifo_overflow = '0;
    fifo_underflow = '0;
    allow_line_cmd = '0;
    rd_outs = '0;
    wr_outs = '0;
    outs_empty = '0;
    joint_mode = '0;
    joint_remote = '0;
    joint_cross = '0;
    page_cross = '0;
    joint_flush = '0;
    reset = 1'b1;  // active-high reset asserted

    // Wait for reset
    #100;

    reset = 1'b0;  // release active-high reset

    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_dma_axi32_core0_ch_reg compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_dma_axi32_core0_ch_reg");
    $finish;
  end

endmodule
