// Auto-generated testbench for prgen_demux8
// Source: prgen_demux8.v
// Generated by blockify generate_tb.py
// Purpose: Compile-check and basic instantiation test

`timescale 1ns/1ps

module tb_prgen_demux8;

  reg [2:0] sel;
  reg [7:0] x;
  wire [63:0] ch_x;

  // DUT instantiation
  prgen_demux8 #(
    // .WIDTH()
  ) dut (
    .sel(sel),
    .x(x),
    .ch_x(ch_x)
  );

  initial begin
    sel = '0;
    x = '0;

    // Wait for reset
    #100;


    // Basic test: wait a few cycles
    #200;

    $display("PASS: tb_prgen_demux8 compile and instantiation test");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #10000;
    $display("TIMEOUT: tb_prgen_demux8");
    $finish;
  end

endmodule
